/**
 * Programme corpus.
 *
 * Days 1-5 are the hand-checked seed built from deck.ts.
 * Days 6-27 are Tatoeba sentences (CC-BY) vocalised by Dicta Nakdan,
 * selected greedily for new-word yield per PROGRAMME.md §1.
 *
 * The generated range has NOT had a native speaker's review yet: Nakdan flags
 * its uncertain words, and those are what a reviewer should look at first.
 * Transliterations and English glosses are empty for generated lines.
 *
 * Do not hand-edit. Regenerate with scripts/build-corpus.mjs.
 */

import type { Line } from "./programme.ts";

export const LINES: Line[] = [
  {
    id: "l-001",
    day: 1,
    he: "?אֵיפֹה הַ___",
    tr: "Eifo ha-___?",
    fr: "Où est le/la ___ ?",
    en: "Where is the ___?",
    words: ["p-eifo"],
    pattern: "p-eifo",
  },
  {
    id: "l-002",
    day: 1,
    he: "___ אֲנִי צָרִיךְ",
    tr: "Ani tsarich ___",
    fr: "J'ai besoin de ___",
    en: "I need ___",
    words: ["p-tsarich"],
    pattern: "p-tsarich",
  },
  {
    id: "l-003",
    day: 1,
    he: "___ אֲנִי רוֹצֶה",
    tr: "Ani rotse ___",
    fr: "Je veux ___",
    en: "I want ___",
    words: ["p-rotse"],
    pattern: "p-rotse",
  },
  {
    id: "l-004",
    day: 1,
    he: "?כַּמָּה זֶה עוֹלֶה",
    tr: "Kama ze ole?",
    fr: "Combien ça coûte ?",
    en: "How much does it cost?",
    words: ["p-kama"],
    pattern: "p-kama",
  },
  {
    id: "l-005",
    day: 1,
    he: "?אֶפְשָׁר",
    tr: "Efshar?",
    fr: "C'est possible ? / Je peux ?",
    en: "Is it possible? / May I?",
    words: ["p-efshar"],
    pattern: "p-efshar",
  },
  {
    id: "l-006",
    day: 1,
    he: "___ יֵשׁ לִי",
    tr: "Yesh li ___",
    fr: "J'ai ___",
    en: "I have ___",
    words: ["p-yesh-li"],
    pattern: "p-yesh-li",
  },
  {
    id: "l-007",
    day: 1,
    he: "אֲנִי לֹא מֵבִין",
    tr: "Ani lo mevin",
    fr: "Je ne comprends pas",
    en: "I don't understand",
    words: ["p-lo-mevin"],
    pattern: "p-lo-mevin",
  },
  {
    id: "l-008",
    day: 1,
    he: "?מָה זֶה",
    tr: "Ma ze?",
    fr: "Qu'est-ce que c'est ?",
    en: "What is this?",
    words: ["p-ma-ze"],
    pattern: "p-ma-ze",
  },
  {
    id: "l-009",
    day: 1,
    he: "?אַתָּה מְדַבֵּר אַנְגְּלִית",
    tr: "Ata medaber anglit?",
    fr: "Tu parles anglais ?",
    en: "Do you speak English?",
    words: ["p-anglit"],
    pattern: "p-anglit",
  },
  {
    id: "l-010",
    day: 1,
    he: "אֲנִי רוֹצֶה קָפֶה",
    tr: "Ani rotse kafe",
    fr: "Je veux un café",
    en: "I want a coffee",
    words: ["w-ani"],
  },
  {
    id: "l-011",
    day: 1,
    he: "הוּא לוֹמֵד",
    tr: "Hu lomed",
    fr: "Il apprend",
    en: "He is learning",
    words: ["w-hu-hi"],
  },
  {
    id: "l-012",
    day: 1,
    he: "אֲנַחְנוּ הוֹלְכִים",
    tr: "Anachnu holchim",
    fr: "Nous allons",
    en: "We are going",
    words: ["w-anachnu"],
  },
  {
    id: "l-013",
    day: 2,
    he: "?אַתֶּם מְדַבְּרִים עִבְרִית",
    tr: "Atem medabrim ivrit?",
    fr: "Vous parlez hébreu ?",
    en: "Do you speak Hebrew?",
    words: ["w-atem-hem"],
  },
  {
    id: "l-014",
    day: 2,
    he: "?מִי זֶה",
    tr: "Mi ze?",
    fr: "Qui est-ce ?",
    en: "Who is that?",
    words: ["w-mi"],
  },
  {
    id: "l-015",
    day: 2,
    he: "?אֵיפֹה הַתַּחֲנָה",
    tr: "Eifo ha-tachana?",
    fr: "Où est la gare ?",
    en: "Where is the station?",
    words: ["w-eifo"],
  },
  {
    id: "l-016",
    day: 2,
    he: "?מָתַי זֶה",
    tr: "Matai ze?",
    fr: "C'est quand ?",
    en: "When is it?",
    words: ["w-matai"],
  },
  {
    id: "l-017",
    day: 2,
    he: "?לָמָּה לֹא",
    tr: "Lama lo?",
    fr: "Pourquoi pas ?",
    en: "Why not?",
    words: ["w-lama"],
  },
  {
    id: "l-018",
    day: 2,
    he: "?אֵיךְ אוֹמְרִים",
    tr: "Eich omrim?",
    fr: "Comment dit-on ?",
    en: "How do you say?",
    words: ["w-eich"],
  },
  {
    id: "l-019",
    day: 2,
    he: "?מֵאַיִן אַתָּה",
    tr: "Me'ayin ata?",
    fr: "D'où viens-tu ?",
    en: "Where are you from?",
    words: ["w-meayin"],
  },
  {
    id: "l-020",
    day: 2,
    he: "יֵשׁ לִי זְמַן",
    tr: "Yesh li zman",
    fr: "J'ai du temps",
    en: "I have time",
    words: ["w-yesh-ein"],
  },
  {
    id: "l-021",
    day: 2,
    he: "אֲנִי צָרִיךְ עֶזְרָה",
    tr: "Ani tsarich ezra",
    fr: "J'ai besoin d'aide",
    en: "I need help",
    words: ["w-tsarich"],
  },
  {
    id: "l-022",
    day: 2,
    he: "אֲנִי יָכוֹל",
    tr: "Ani yachol",
    fr: "Je peux",
    en: "I can",
    words: ["w-yachol"],
  },
  {
    id: "l-023",
    day: 2,
    he: "אֲנִי הוֹלֵךְ הַבַּיְתָה",
    tr: "Ani holech habaita",
    fr: "Je rentre à la maison",
    en: "I'm going home",
    words: ["w-holech"],
  },
  {
    id: "l-024",
    day: 2,
    he: "?אַתָּה בָּא",
    tr: "Ata ba?",
    fr: "Tu viens ?",
    en: "Are you coming?",
    words: ["w-ba"],
  },
  {
    id: "l-025",
    day: 3,
    he: "אֲנִי לֹא יוֹדֵעַ",
    tr: "Ani lo yode'a",
    fr: "Je ne sais pas",
    en: "I don't know",
    words: ["w-yodea"],
  },
  {
    id: "l-026",
    day: 3,
    he: "?אֵיפֹה אַתָּה גָּר",
    tr: "Eifo ata gar?",
    fr: "Où habites-tu ?",
    en: "Where do you live?",
    words: ["w-gar"],
  },
  {
    id: "l-027",
    day: 3,
    he: "אֲנִי עוֹבֵד",
    tr: "Ani oved",
    fr: "Je travaille",
    en: "I work",
    words: ["w-oved"],
  },
  {
    id: "l-028",
    day: 3,
    he: "אֲנִי לוֹמֵד עִבְרִית",
    tr: "Ani lomed ivrit",
    fr: "J'apprends l'hébreu",
    en: "I'm learning Hebrew",
    words: ["w-lomed"],
  },
  {
    id: "l-029",
    day: 3,
    he: "אֲנִי מְדַבֵּר קְצָת",
    tr: "Ani medaber ktsat",
    fr: "Je parle un peu",
    en: "I speak a little",
    words: ["w-medaber"],
  },
  {
    id: "l-030",
    day: 3,
    he: "קָפֶה וְעוּגָה",
    tr: "Kafe ve-uga",
    fr: "Un café et un gâteau",
    en: "Coffee and cake",
    words: ["w-ve"],
  },
  {
    id: "l-031",
    day: 3,
    he: "אֲנִי רוֹצֶה אֲבָל אֵין לִי זְמַן",
    tr: "Ani rotse aval ein li zman",
    fr: "Je veux mais je n'ai pas le temps",
    en: "I want to but I have no time",
    words: ["w-aval"],
  },
  {
    id: "l-032",
    day: 3,
    he: "גַּם אֲנִי",
    tr: "Gam ani",
    fr: "Moi aussi",
    en: "Me too",
    words: ["w-gam"],
  },
  {
    id: "l-033",
    day: 3,
    he: "כֵּן, בְּבַקָּשָׁה",
    tr: "Ken, bevakasha",
    fr: "Oui, s'il te plaît",
    en: "Yes, please",
    words: ["w-ken-lo"],
  },
  {
    id: "l-034",
    day: 3,
    he: "קָפֶה בְּלִי סֻכָּר",
    tr: "Kafe bli sukar",
    fr: "Un café sans sucre",
    en: "Coffee without sugar",
    words: ["w-im-bli"],
  },
  {
    id: "l-035",
    day: 3,
    he: "כִּי אֲנִי לוֹמֵד",
    tr: "Ki ani lomed",
    fr: "Parce que j'apprends",
    en: "Because I'm learning",
    words: ["w-ki"],
  },
  {
    id: "l-036",
    day: 3,
    he: "הַיּוֹם אֲנִי עוֹבֵד",
    tr: "Hayom ani oved",
    fr: "Aujourd'hui je travaille",
    en: "Today I'm working",
    words: ["w-hayom"],
  },
  {
    id: "l-037",
    day: 4,
    he: "אֲנִי מְדַבֵּר קְצָת עִבְרִית",
    tr: "Ani medaber ktsat ivrit",
    fr: "Je parle un peu hébreu",
    en: "I speak a little Hebrew",
    words: ["i-ktsat"],
  },
  {
    id: "l-038",
    day: 4,
    he: "?מָה הַשֵּׁם שֶׁלְּךָ",
    tr: "Ma ha-shem shelcha?",
    fr: "Comment tu t'appelles ?",
    en: "What's your name?",
    words: ["i-ma-hashem"],
  },
  {
    id: "l-039",
    day: 4,
    he: "___ שְׁמִי",
    tr: "Shmi ___",
    fr: "Je m'appelle ___",
    en: "My name is ___",
    words: ["i-shmi"],
  },
  {
    id: "l-040",
    day: 4,
    he: "נָעִים מְאוֹד",
    tr: "na'im me'od",
    fr: "enchanté",
    en: "nice to meet you",
    words: ["i-naim"],
  },
  {
    id: "l-041",
    day: 4,
    he: "?מָה שְׁלוֹמְךָ",
    tr: "Ma shlomcha?",
    fr: "Comment vas-tu ?",
    en: "How are you?",
    words: ["i-ma-shlomcha"],
  },
  {
    id: "l-042",
    day: 4,
    he: "?מָה נִשְׁמָע",
    tr: "Ma nishma?",
    fr: "Quoi de neuf ?",
    en: "What's up?",
    words: ["i-ma-nishma"],
  },
  {
    id: "l-043",
    day: 4,
    he: "___ אֲנִי מִ",
    tr: "Ani mi-___",
    fr: "Je viens de ___",
    en: "I'm from ___",
    words: ["i-ani-mi"],
  },
  {
    id: "l-044",
    day: 4,
    he: "?בֶּן כַּמָּה אַתָּה",
    tr: "Ben kama ata?",
    fr: "Quel âge as-tu ?",
    en: "How old are you?",
    words: ["i-ben-kama"],
  },
  {
    id: "l-045",
    day: 4,
    he: "עוֹלֶה חָדָשׁ",
    tr: "oleh chadash",
    fr: "nouvel immigrant",
    en: "new immigrant",
    words: ["i-oleh"],
  },
  {
    id: "l-046",
    day: 4,
    he: "יֵשׁ לִי שְׁנֵי יְלָדִים",
    tr: "Yesh li shnei yeladim",
    fr: "J'ai deux enfants",
    en: "I have two children",
    words: ["f-yesh-li-yeladim"],
  },
  {
    id: "l-047",
    day: 4,
    he: "___ אֲנִי גָּר בְּ",
    tr: "Ani gar be-___",
    fr: "J'habite à ___",
    en: "I live in ___",
    words: ["h-gar-be"],
  },
  {
    id: "l-048",
    day: 4,
    he: "לִפְנוֹת יָמִינָה",
    tr: "Lifnot yamina",
    fr: "Tourner à droite",
    en: "Turn right",
    words: ["d-yamina"],
  },
  {
    id: "l-049",
    day: 5,
    he: "לִפְנוֹת שְׂמֹאלָה",
    tr: "Lifnot smola",
    fr: "Tourner à gauche",
    en: "Turn left",
    words: ["d-smola"],
  },
  {
    id: "l-050",
    day: 5,
    he: "תֵּלֵךְ יָשָׁר",
    tr: "Telech yashar",
    fr: "Va tout droit",
    en: "Go straight",
    words: ["d-yashar"],
  },
  {
    id: "l-051",
    day: 5,
    he: "?זֶה קָרוֹב",
    tr: "Ze karov?",
    fr: "C'est près ?",
    en: "Is it near?",
    words: ["d-karov"],
  },
  {
    id: "l-052",
    day: 5,
    he: "זֶה רָחוֹק מִכָּאן",
    tr: "Ze rachok mikan",
    fr: "C'est loin d'ici",
    en: "It's far from here",
    words: ["d-rachok"],
  },
  {
    id: "l-053",
    day: 5,
    he: "אֲנִי כָּאן",
    tr: "Ani kan",
    fr: "Je suis ici",
    en: "I'm here",
    words: ["d-kan"],
  },
  {
    id: "l-054",
    day: 5,
    he: "זֶה שָׁם",
    tr: "Ze sham",
    fr: "C'est là-bas",
    en: "It's over there",
    words: ["d-sham"],
  },
  {
    id: "l-055",
    day: 5,
    he: "לְיַד הַתַּחֲנָה",
    tr: "Leyad ha-tachana",
    fr: "À côté de la gare",
    en: "Next to the station",
    words: ["d-leyad"],
  },
  {
    id: "l-056",
    day: 5,
    he: "מוּל הַבַּיִת",
    tr: "Mul ha-bayit",
    fr: "En face de la maison",
    en: "Opposite the house",
    words: ["d-mul"],
  },
  {
    id: "l-057",
    day: 5,
    he: "בֵּין הַבַּיִת וְהַתַּחֲנָה",
    tr: "Bein ha-bayit ve-ha-tachana",
    fr: "Entre la maison et la gare",
    en: "Between the house and the station",
    words: ["d-bein"],
  },
  {
    id: "l-058",
    day: 5,
    he: "?___ אֵיךְ מַגִּיעִים לְ",
    tr: "Eich magi'im le-___?",
    fr: "Comment on va à ___ ?",
    en: "How do you get to ___?",
    words: ["d-eich-magiim"],
  },
  {
    id: "l-059",
    day: 6,
    he: "מָה אַתָּה עוֹשֶׂה?",
    tr: "",
    fr: "Tu fais quoi ?",
    en: "",
    words: ["מה","אתה","עושה"],
  },
  {
    id: "l-060",
    day: 6,
    he: "תַּחֲשֹׁב עַל זֶה.",
    tr: "",
    fr: "Pensez-y.",
    en: "",
    words: ["תחשב","על","זה"],
  },
  {
    id: "l-061",
    day: 6,
    he: "בַּתְּמוּנָה כֻּלָּם מְחַיְּכִים.",
    tr: "",
    fr: "Tout le monde sourit sur la photographie.",
    en: "",
    words: ["בתמונה","כלם","מחיכים"],
  },
  {
    id: "l-062",
    day: 6,
    he: "אַל תִּשְׁכַּח אוֹתָנוּ!",
    tr: "",
    fr: "Ne nous oublie pas !",
    en: "",
    words: ["אל","תשכח","אותנו"],
  },
  {
    id: "l-063",
    day: 6,
    he: "אַתְּ רוֹצָה לָלֶכֶת?",
    tr: "",
    fr: "Voulez-vous y aller ?",
    en: "",
    words: ["את","רוצה","ללכת"],
  },
  {
    id: "l-064",
    day: 6,
    he: "אַחֲרֵי הַמָּוֶת, הָרוֹפֵא.",
    tr: "",
    fr: "Après la mort, le docteur.",
    en: "",
    words: ["אחרי","המות","הרופא"],
  },
  {
    id: "l-065",
    day: 6,
    he: "תִּהְיֶה דִּיפְּלוֹמָט טוֹב.",
    tr: "",
    fr: "Tu ferais un bon diplomate.",
    en: "",
    words: ["תהיה","דיפלומט","טוב"],
  },
  {
    id: "l-066",
    day: 6,
    he: "תִּהְיִי דִּיפְּלוֹמָטִית טוֹבָה.",
    tr: "",
    fr: "Tu ferais un bon diplomate.",
    en: "",
    words: ["תהיי","דיפלומטית","טובה"],
  },
  {
    id: "l-067",
    day: 6,
    he: "הִיא צְעִירָה כָּמוֹנִי.",
    tr: "",
    fr: "Elle est aussi jeune que moi.",
    en: "",
    words: ["היא","צעירה","כמוני"],
  },
  {
    id: "l-068",
    day: 6,
    he: "שָׁחֹר הוֹלֵם אוֹתְךָ.",
    tr: "",
    fr: "Le noir te va bien.",
    en: "",
    words: ["שחר","הולם","אותך"],
  },
  {
    id: "l-069",
    day: 6,
    he: "תֵּן לוֹ זְמַן.",
    tr: "",
    fr: "Donne-lui du temps.",
    en: "",
    words: ["תן","לו","זמן"],
  },
  {
    id: "l-070",
    day: 6,
    he: "יָרְדוּ גְּשָׁמִים עַזִּים.",
    tr: "",
    fr: "Il a fortement plu.",
    en: "",
    words: ["ירדו","גשמים","עזים"],
  },
  {
    id: "l-071",
    day: 8,
    he: "אֲנִי עָסוּק כָּרֶגַע.",
    tr: "",
    fr: "Je suis occupé maintenant.",
    en: "",
    words: ["אני","עסוק","כרגע"],
  },
  {
    id: "l-072",
    day: 8,
    he: "בַּסְּתָו הֶעָלִים מַצְהִיבִים.",
    tr: "",
    fr: "En automne, les feuilles deviennent jaunes.",
    en: "",
    words: ["בסתו","העלים","מצהיבים"],
  },
  {
    id: "l-073",
    day: 8,
    he: "סְלִיחָה, הָלַכְתִּי לְאִבּוּד.",
    tr: "",
    fr: "Excusez-moi, je me suis perdu.",
    en: "",
    words: ["סליחה","הלכתי","לאבוד"],
  },
  {
    id: "l-074",
    day: 8,
    he: "הָיִיתִי בּוֹדֵד בִּלְעָדֶיהָ.",
    tr: "",
    fr: "J'étais seul sans elle.",
    en: "",
    words: ["הייתי","בודד","בלעדיה"],
  },
  {
    id: "l-075",
    day: 8,
    he: "אֶתְמוֹל קָנִיתִי סֵפֶר.",
    tr: "",
    fr: "Hier j'ai acheté un livre.",
    en: "",
    words: ["אתמול","קניתי","ספר"],
  },
  {
    id: "l-076",
    day: 8,
    he: "הַנַּעֲלַיִם שֶׁלָּךְ כָּאן.",
    tr: "",
    fr: "Tes chaussures sont ici.",
    en: "",
    words: ["הנעלים","שלך","כאן"],
  },
  {
    id: "l-077",
    day: 8,
    he: "לֹא נִכְנַסְתִּי לִפְרָטִים.",
    tr: "",
    fr: "Je ne suis pas entré dans les détails.",
    en: "",
    words: ["לא","נכנסתי","לפרטים"],
  },
  {
    id: "l-078",
    day: 8,
    he: "הָעוֹלָם מָלֵא אִידְיוֹטִים.",
    tr: "",
    fr: "Le monde est plein d'idiots.",
    en: "",
    words: ["העולם","מלא","אידיוטים"],
  },
  {
    id: "l-079",
    day: 8,
    he: "בּוֹא נִסַּע בָּאוֹטוֹבּוּס.",
    tr: "",
    fr: "Prenons un bus.",
    en: "",
    words: ["בוא","נסע","באוטובוס"],
  },
  {
    id: "l-080",
    day: 8,
    he: "נוֹלַדְתִּי וְגָדַלְתִּי בְּטוֹקְיוֹ.",
    tr: "",
    fr: "Je suis né et j'ai été élevé à Tokyo.",
    en: "",
    words: ["נולדתי","וגדלתי","בטוקיו"],
  },
  {
    id: "l-081",
    day: 8,
    he: "הַבֹּקֶר קַמְתִּי מְאֻחָר.",
    tr: "",
    fr: "Je me suis levé tard ce matin.",
    en: "",
    words: ["הבקר","קמתי","מאחר"],
  },
  {
    id: "l-082",
    day: 8,
    he: "אָז אֵיפֹה הָיִיתָ?",
    tr: "",
    fr: "Où étais-tu donc ?",
    en: "",
    words: ["אז","איפה","היית"],
  },
  {
    id: "l-083",
    day: 9,
    he: "עוֹד מַאֲמָץ קָטָן.",
    tr: "",
    fr: "Encore un petit peu.",
    en: "",
    words: ["עוד","מאמץ","קטן"],
  },
  {
    id: "l-084",
    day: 9,
    he: "הָבָה נֵשֵׁב בַּדֶּשֶׁא",
    tr: "",
    fr: "Asseyons-nous sur l'herbe.",
    en: "",
    words: ["הבה","נשב","בדשא"],
  },
  {
    id: "l-085",
    day: 9,
    he: "אֲנַחְנוּ נוֹטִים לִטְעוֹת.",
    tr: "",
    fr: "Nous avons tendance à faire des erreurs.",
    en: "",
    words: ["אנחנו","נוטים","לטעות"],
  },
  {
    id: "l-086",
    day: 9,
    he: "זוֹהִי הַשְּׁאֵלָה שֶׁלִּי.",
    tr: "",
    fr: "C'est ma question.",
    en: "",
    words: ["זוהי","השאלה","שלי"],
  },
  {
    id: "l-087",
    day: 9,
    he: "קָרָאתִי בְּמֶשֶׁךְ שָׁעָה.",
    tr: "",
    fr: "J'ai lu pendant 1 heure.",
    en: "",
    words: ["קראתי","במשך","שעה"],
  },
  {
    id: "l-088",
    day: 9,
    he: "אוֹמְרִים שֶׁהָאַהֲבָה עִוֶּרֶת.",
    tr: "",
    fr: "On dit que l'amour est aveugle.",
    en: "",
    words: ["אומרים","שהאהבה","עורת"],
  },
  {
    id: "l-089",
    day: 9,
    he: "בִּקַּרְתִּי בְּקִיוֹטוֹ פַּעֲמַיִם.",
    tr: "",
    fr: "J'ai été à Kyoto deux fois.",
    en: "",
    words: ["בקרתי","בקיוטו","פעמים"],
  },
  {
    id: "l-090",
    day: 9,
    he: "הַלֶּחֶם הַזֶּה טָעִים.",
    tr: "",
    fr: "Ce pain est délicieux.",
    en: "",
    words: ["הלחם","הזה","טעים"],
  },
  {
    id: "l-091",
    day: 9,
    he: "קָשֶׁה לִי בְּמָתֵמָטִיקָה.",
    tr: "",
    fr: "Les mathématiques sont difficiles pour moi.",
    en: "",
    words: ["קשה","לי","במתמטיקה"],
  },
  {
    id: "l-092",
    day: 9,
    he: "יָשַׁנְתִּי יוֹתֵר מִדַּי.",
    tr: "",
    fr: "J'ai trop dormi.",
    en: "",
    words: ["ישנתי","יותר","מדי"],
  },
  {
    id: "l-093",
    day: 9,
    he: "כַּמָּה יָפֶה אֲחוֹתְךָ!",
    tr: "",
    fr: "Comme ta sœur est jolie !",
    en: "",
    words: ["כמה","יפה","אחותך"],
  },
  {
    id: "l-094",
    day: 9,
    he: "נִזְקַקְתִּי בְּדִיּוּק לָזֶה.",
    tr: "",
    fr: "C'est précisément cela dont j'avais besoin.",
    en: "",
    words: ["נזקקתי","בדיוק","לזה"],
  },
  {
    id: "l-095",
    day: 10,
    he: "עֵינֶיהָ הוּצְפוּ בִּדְמָעוֹת.",
    tr: "",
    fr: "Ses yeux étaient remplis de larmes.",
    en: "",
    words: ["עיניה","הוצפו","בדמעות"],
  },
  {
    id: "l-096",
    day: 10,
    he: "הָאֲנָשִׁים הָלְכוּ בְּעִקְבוֹתָיו.",
    tr: "",
    fr: "Les hommes le suivirent.",
    en: "",
    words: ["האנשים","הלכו","בעקבותיו"],
  },
  {
    id: "l-097",
    day: 10,
    he: "חָתוּל יָשֵׁן בְּשֶׁקֶט.",
    tr: "",
    fr: "Un chat dort tranquillement.",
    en: "",
    words: ["חתול","ישן","בשקט"],
  },
  {
    id: "l-098",
    day: 10,
    he: "הַשָּׁעָה כְּבָר שֶׁבַע.",
    tr: "",
    fr: "Il est déjà 7 heures.",
    en: "",
    words: ["השעה","כבר","שבע"],
  },
  {
    id: "l-099",
    day: 10,
    he: "הַגַּנָּב הֻסְגַּר לַמִּשְׁטָרָה.",
    tr: "",
    fr: "Le voleur fut confié à la police.",
    en: "",
    words: ["הגנב","הסגר","למשטרה"],
  },
  {
    id: "l-100",
    day: 10,
    he: "עָבַרְתִּי לַיְלָה לָבָן.",
    tr: "",
    fr: "J'ai passé une nuit blanche.",
    en: "",
    words: ["עברתי","לילה","לבן"],
  },
  {
    id: "l-101",
    day: 10,
    he: "הָעִשּׁוּן רַע עֲבוּרְךָ.",
    tr: "",
    fr: "Fumer est mauvais pour toi.",
    en: "",
    words: ["העשון","רע","עבורך"],
  },
  {
    id: "l-102",
    day: 10,
    he: "הַשָּׁעוֹן עָמַד מִלֶּכֶת.",
    tr: "",
    fr: "L'horloge s'est arrêtée.",
    en: "",
    words: ["השעון","עמד","מלכת"],
  },
  {
    id: "l-103",
    day: 10,
    he: "אָמַרְתִּי לְאִשְׁתִּי שֶׁתִּזְדָּרֵז.",
    tr: "",
    fr: "Je dis à ma femme de se dépêcher.",
    en: "",
    words: ["אמרתי","לאשתי","שתזדרז"],
  },
  {
    id: "l-104",
    day: 10,
    he: "גִּלִּיתִי שְׁגִיאָה חֲמוּרָה.",
    tr: "",
    fr: "J'ai détecté une grosse erreur.",
    en: "",
    words: ["גליתי","שגיאה","חמורה"],
  },
  {
    id: "l-105",
    day: 10,
    he: "הוֹ, תּוֹדָה, יַקִּירִי.",
    tr: "",
    fr: "Ah, je vous remercie, mon cher.",
    en: "",
    words: ["הו","תודה","יקירי"],
  },
  {
    id: "l-106",
    day: 10,
    he: "תִּתְקַשֵּׁר מִיָּד לְטוֹם.",
    tr: "",
    fr: "Appelle Tom tout de suite.",
    en: "",
    words: ["תתקשר","מיד","לטום"],
  },
  {
    id: "l-107",
    day: 11,
    he: "אֵרְעָה תְּאוּנַת דְּרָכִים.",
    tr: "",
    fr: "Il y a eu un accident de la route.",
    en: "",
    words: ["ארעה","תאונת","דרכים"],
  },
  {
    id: "l-108",
    day: 11,
    he: "חַג הַמּוֹלָד מִתְקָרֵב.",
    tr: "",
    fr: "Noël approche.",
    en: "",
    words: ["חג","המולד","מתקרב"],
  },
  {
    id: "l-109",
    day: 11,
    he: "אֵיךְ קָרָה שֶׁהִכַּרְתֶּם?",
    tr: "",
    fr: "Comment se fait-il que vous vous connaissiez ?",
    en: "",
    words: ["איך","קרה","שהכרתם"],
  },
  {
    id: "l-110",
    day: 11,
    he: "מָחָר אָקוּם מֻקְדָּם.",
    tr: "",
    fr: "Je me lèverai tôt demain.",
    en: "",
    words: ["מחר","אקום","מקדם"],
  },
  {
    id: "l-111",
    day: 11,
    he: "אָכַלְתִּי רֶבַע מֵהָעוּגָה.",
    tr: "",
    fr: "J'ai mangé le quart du gâteau.",
    en: "",
    words: ["אכלתי","רבע","מהעוגה"],
  },
  {
    id: "l-112",
    day: 11,
    he: "אַנְגְּלִיָּה גֵּאָה בִּמְשׁוֹרְרֶיהָ.",
    tr: "",
    fr: "L'Angleterre est fière de ses poètes.",
    en: "",
    words: ["אנגליה","גאה","במשורריה"],
  },
  {
    id: "l-113",
    day: 11,
    he: "אַגִּיעַ בְּמִקְרֵה הַצֹּרֶךְ.",
    tr: "",
    fr: "Je viendrai si nécessaire.",
    en: "",
    words: ["אגיע","במקרה","הצרך"],
  },
  {
    id: "l-114",
    day: 11,
    he: "אֵינֶנִּי מַכִּיר אוֹתוֹ.",
    tr: "",
    fr: "Je ne le connais pas.",
    en: "",
    words: ["אינני","מכיר","אותו"],
  },
  {
    id: "l-115",
    day: 11,
    he: "שְׁנֵי הָאַחִים נִפְטְרוּ.",
    tr: "",
    fr: "Les deux frères sont morts.",
    en: "",
    words: ["שני","האחים","נפטרו"],
  },
  {
    id: "l-116",
    day: 11,
    he: "הַסּוֹפֵר מֻכָּר לָנוּ.",
    tr: "",
    fr: "L'écrivain nous est connu.",
    en: "",
    words: ["הסופר","מכר","לנו"],
  },
  {
    id: "l-117",
    day: 11,
    he: "צָרְפַת גּוֹבֶלֶת בְּאִיטַלְיָה.",
    tr: "",
    fr: "La France a une frontière avec l'Italie.",
    en: "",
    words: ["צרפת","גובלת","באיטליה"],
  },
  {
    id: "l-118",
    day: 11,
    he: "שִׁכּוֹר נָפַל מֵהַמַּדְרֵגוֹת.",
    tr: "",
    fr: "Un homme ivre est tombé des escaliers.",
    en: "",
    words: ["שכור","נפל","מהמדרגות"],
  },
  {
    id: "l-119",
    day: 12,
    he: "חָלַקְתִּי עִמּוֹ חֶדֶר.",
    tr: "",
    fr: "J'ai partagé une chambre avec lui.",
    en: "",
    words: ["חלקתי","עמו","חדר"],
  },
  {
    id: "l-120",
    day: 12,
    he: "זֹאת הַשְּׁכֵנָה שֶׁלָּנוּ.",
    tr: "",
    fr: "C'est notre voisine.",
    en: "",
    words: ["זאת","השכנה","שלנו"],
  },
  {
    id: "l-121",
    day: 12,
    he: "אֶכְתֹּב מִכְתָּבִי לְג'וּדִי.",
    tr: "",
    fr: "J'écrirai une lettre à Judy.",
    en: "",
    words: ["אכתב","מכתבי","לגודי"],
  },
  {
    id: "l-122",
    day: 12,
    he: "תֹּם אוֹהֵב עַגְבָנִיּוֹת?",
    tr: "",
    fr: "Tom aime-t-il les tomates ?",
    en: "",
    words: ["תם","אוהב","עגבניות"],
  },
  {
    id: "l-123",
    day: 12,
    he: "אֵינִי מִתְמַצֵּא בִּפְרָטִים.",
    tr: "",
    fr: "Je ne connais pas les détails.",
    en: "",
    words: ["איני","מתמצא","בפרטים"],
  },
  {
    id: "l-124",
    day: 12,
    he: "בְּבַקְבּוּק אוֹ בְּכוֹס?",
    tr: "",
    fr: "À la bouteille ou au verre ?",
    en: "",
    words: ["בבקבוק","או","בכוס"],
  },
  {
    id: "l-125",
    day: 12,
    he: "הַמִּכְתָּב הֶעֱצִיב אוֹתָהּ.",
    tr: "",
    fr: "La lettre la rendit triste.",
    en: "",
    words: ["המכתב","העציב","אותה"],
  },
  {
    id: "l-126",
    day: 12,
    he: "חֲצִי מֵהַתַּלְמִידִים נֶעְדָּרִים.",
    tr: "",
    fr: "La moitié des étudiants sont absents.",
    en: "",
    words: ["חצי","מהתלמידים","נעדרים"],
  },
  {
    id: "l-127",
    day: 12,
    he: "חֲתוּלִים רוֹאִים בַּחֹשֶׁךְ.",
    tr: "",
    fr: "Les chats peuvent voir dans l'obscurité.",
    en: "",
    words: ["חתולים","רואים","בחשך"],
  },
  {
    id: "l-128",
    day: 12,
    he: "עָדִיף שֶׁתַּתְחִיל מִיָּד.",
    tr: "",
    fr: "Tu ferais mieux de commencer tout de suite.",
    en: "",
    words: ["עדיף","שתתחיל","מיד"],
  },
  {
    id: "l-129",
    day: 12,
    he: "לָמָּה שֶׁתִּהְיֶה מֻפְתָּע?",
    tr: "",
    fr: "Pourquoi devrais-tu être surpris ?",
    en: "",
    words: ["למה","שתהיה","מפתע"],
  },
  {
    id: "l-130",
    day: 12,
    he: "זוֹ מַמָּשׁ שַׁעֲרוּרִיָּה!",
    tr: "",
    fr: "C’est un véritable scandale !",
    en: "",
    words: ["זו","ממש","שערוריה"],
  },
  {
    id: "l-131",
    day: 13,
    he: "בִּזְכוּת עֶזְרָתְךָ, הִצְלַחְתִּי.",
    tr: "",
    fr: "Grâce à ton aide, j'ai pu réussir.",
    en: "",
    words: ["בזכות","עזרתך","הצלחתי"],
  },
  {
    id: "l-132",
    day: 13,
    he: "הַדֶּלֶת נִפְתְּחָה בְּעַצְמָהּ.",
    tr: "",
    fr: "La porte s'est ouverte toute seule.",
    en: "",
    words: ["הדלת","נפתחה","בעצמה"],
  },
  {
    id: "l-133",
    day: 13,
    he: "דּוֹקְטוֹר, רָפָא אוֹתִי.",
    tr: "",
    fr: "Docteur guérissez-moi.",
    en: "",
    words: ["דוקטור","רפא","אותי"],
  },
  {
    id: "l-134",
    day: 13,
    he: "לְבַסּוֹף, אֵדִיפּוּס הֵשִׁיב.",
    tr: "",
    fr: "Finalement, Œdipe répondit.",
    en: "",
    words: ["לבסוף","אדיפוס","השיב"],
  },
  {
    id: "l-135",
    day: 13,
    he: "הִנֵּה מִכְתָּב בִּשְׁבִילְךָ.",
    tr: "",
    fr: "Voilà une lettre pour toi.",
    en: "",
    words: ["הנה","מכתב","בשבילך"],
  },
  {
    id: "l-136",
    day: 13,
    he: "הֵם נִסּוּ לִבְרֹחַ.",
    tr: "",
    fr: "Ils cherchaient à s'enfuir.",
    en: "",
    words: ["הם","נסו","לברח"],
  },
  {
    id: "l-137",
    day: 13,
    he: "כָּל הָאוֹטוֹבּוּסִים מְלֵאִים.",
    tr: "",
    fr: "Tous les bus sont pleins.",
    en: "",
    words: ["כל","האוטובוסים","מלאים"],
  },
  {
    id: "l-138",
    day: 13,
    he: "הַבֵּט! הָרַכֶּבֶת הִגִּיעָה!",
    tr: "",
    fr: "Regarde ! Le train est arrivé !",
    en: "",
    words: ["הבט","הרכבת","הגיעה"],
  },
  {
    id: "l-139",
    day: 13,
    he: "הָעֵט חֲזָקָה מֵהַחֶרֶב.",
    tr: "",
    fr: "La plume est plus forte que l'épée.",
    en: "",
    words: ["העט","חזקה","מהחרב"],
  },
  {
    id: "l-140",
    day: 13,
    he: "הֶחְלַטְתָּ לִנְסֹעַ לְיַפָּן?",
    tr: "",
    fr: "As-tu décidé d'aller au Japon ?",
    en: "",
    words: ["החלטת","לנסע","ליפן"],
  },
  {
    id: "l-141",
    day: 13,
    he: "לִבִּי חָדַל לִפְעֹם.",
    tr: "",
    fr: "Mon cœur s'est arrêté de battre.",
    en: "",
    words: ["לבי","חדל","לפעם"],
  },
  {
    id: "l-142",
    day: 13,
    he: "אַתֶּם מְדַבְּרִים סִינִית?",
    tr: "",
    fr: "Parlez-vous chinois ?",
    en: "",
    words: ["אתם","מדברים","סינית"],
  },
  {
    id: "l-143",
    day: 15,
    he: "טָעִיתִי בְּקֶשֶׁר לְעַצְמִי.",
    tr: "",
    fr: "Je me suis trompé quant à moi-même.",
    en: "",
    words: ["טעיתי","בקשר","לעצמי"],
  },
  {
    id: "l-144",
    day: 15,
    he: "הִצַּגְתִּי שְׁאֵלָה לְטוֹנִי.",
    tr: "",
    fr: "J'ai posé une question à Tony.",
    en: "",
    words: ["הצגתי","שאלה","לטוני"],
  },
  {
    id: "l-145",
    day: 15,
    he: "אֵילוּ נַעֲלַיִם תִּנְעֲלִי?",
    tr: "",
    fr: "Quelles chaussures allez-vous mettre ?",
    en: "",
    words: ["אילו","נעלים","תנעלי"],
  },
  {
    id: "l-146",
    day: 15,
    he: "הֶעֱלֵיתִי בְּמִשְׁקָל לָאַחֲרוֹנָה.",
    tr: "",
    fr: "J'ai pris du poids récemment.",
    en: "",
    words: ["העליתי","במשקל","לאחרונה"],
  },
  {
    id: "l-147",
    day: 15,
    he: "תַּקְלִיק כְּדֵי לַעֲרֹךְ!",
    tr: "",
    fr: "Cliquez pour éditer !",
    en: "",
    words: ["תקליק","כדי","לערך"],
  },
  {
    id: "l-148",
    day: 15,
    he: "הַתִּינוֹק חִיֵּךְ אֵלַי.",
    tr: "",
    fr: "Le bébé me sourit.",
    en: "",
    words: ["התינוק","חיך","אלי"],
  },
  {
    id: "l-149",
    day: 15,
    he: "בּוֹאוּ נְשַׂחֵק בְּמַשֶּׁהוּ.",
    tr: "",
    fr: "Jouons à quelque chose.",
    en: "",
    words: ["בואו","נשחק","במשהו"],
  },
  {
    id: "l-150",
    day: 15,
    he: "עָבַדְתִּי הַרְבֵּה הַשָּׁבוּעַ.",
    tr: "",
    fr: "J'ai beaucoup travaillé cette semaine.",
    en: "",
    words: ["עבדתי","הרבה","השבוע"],
  },
  {
    id: "l-151",
    day: 15,
    he: "מַהוּ שְׂכָרְךָ לְשָׁעָה?",
    tr: "",
    fr: "Combien es-tu payé de l'heure ?",
    en: "",
    words: ["מהו","שכרך","לשעה"],
  },
  {
    id: "l-152",
    day: 15,
    he: "לַמְּקוֹמוֹת, הִכּוֹן, רוּץ!",
    tr: "",
    fr: "À vos marques, prêts, partez !",
    en: "",
    words: ["למקומות","הכון","רוץ"],
  },
  {
    id: "l-153",
    day: 15,
    he: "נֶשֶׁר עָף בַּשָּׁמַיִם.",
    tr: "",
    fr: "Un aigle vole dans le ciel.",
    en: "",
    words: ["נשר","עף","בשמים"],
  },
  {
    id: "l-154",
    day: 15,
    he: "הַחֲנוּת נִסְגֶּרֶת בְּשֶׁבַע.",
    tr: "",
    fr: "Le magasin ferme à 7 heures.",
    en: "",
    words: ["החנות","נסגרת","בשבע"],
  },
  {
    id: "l-155",
    day: 16,
    he: "בּוֹאִי נֵלֵךְ לַקּוֹלְנוֹעַ.",
    tr: "",
    fr: "Allons au cinéma.",
    en: "",
    words: ["בואי","נלך","לקולנוע"],
  },
  {
    id: "l-156",
    day: 16,
    he: "קִבַּלְתִּי מַכַּת שֶׁמֶשׁ.",
    tr: "",
    fr: "J'ai attrapé un coup de soleil.",
    en: "",
    words: ["קבלתי","מכת","שמש"],
  },
  {
    id: "l-157",
    day: 16,
    he: "הָאָטוֹמִים יוֹצְרִים מוֹלֵקוּלוֹת.",
    tr: "",
    fr: "Les atomes forment des molécules.",
    en: "",
    words: ["האטומים","יוצרים","מולקולות"],
  },
  {
    id: "l-158",
    day: 16,
    he: "דַּי לְחַכִּימָא בִּרְמִיזָא.",
    tr: "",
    fr: "Une allusion suffit au sage.",
    en: "",
    words: ["די","לחכימא","ברמיזא"],
  },
  {
    id: "l-159",
    day: 16,
    he: "הִגַּעְנוּ לַכְּפָר בַּחֲצוֹת.",
    tr: "",
    fr: "Nous avons atteint le village à minuit.",
    en: "",
    words: ["הגענו","לכפר","בחצות"],
  },
  {
    id: "l-160",
    day: 16,
    he: "הַפֵּרוֹת נִמְצָאִים בַּסַּל.",
    tr: "",
    fr: "Les fruits sont dans le panier.",
    en: "",
    words: ["הפרות","נמצאים","בסל"],
  },
  {
    id: "l-161",
    day: 16,
    he: "בְּגָדוֹל, דְּבָרֶיהָ מְדֻיָּקִים.",
    tr: "",
    fr: "Généralement, ce qu'elle dit est exact.",
    en: "",
    words: ["בגדול","דבריה","מדיקים"],
  },
  {
    id: "l-162",
    day: 16,
    he: "אֶחֱזֹר לִפְנֵי תֵּשַׁע.",
    tr: "",
    fr: "Je serai de retour avant neuf heures.",
    en: "",
    words: ["אחזר","לפני","תשע"],
  },
  {
    id: "l-163",
    day: 16,
    he: "הַחַיָּל נֶהֱרַג בַּקְּרָב.",
    tr: "",
    fr: "Le soldat a été tué au combat.",
    en: "",
    words: ["החיל","נהרג","בקרב"],
  },
  {
    id: "l-164",
    day: 16,
    he: "שֶׁהַכֶּלֶב יִשָּׁאֵר בַּחוּץ!",
    tr: "",
    fr: "Que le chien reste dehors !",
    en: "",
    words: ["שהכלב","ישאר","בחוץ"],
  },
  {
    id: "l-165",
    day: 16,
    he: "הַדְּיוֹ נִגְמַר בָּעֵט.",
    tr: "",
    fr: "Le stylo n'a plus d'encre.",
    en: "",
    words: ["הדיו","נגמר","בעט"],
  },
  {
    id: "l-166",
    day: 16,
    he: "הַבִּנְיָן נִמְצָא בִּבְנִיָּה.",
    tr: "",
    fr: "Le bâtiment est en construction.",
    en: "",
    words: ["הבנין","נמצא","בבניה"],
  },
  {
    id: "l-167",
    day: 17,
    he: "בַּחֲלוֹמִי, פָּגַשְׁתִּי זְאֵב.",
    tr: "",
    fr: "J'ai rencontré un loup en rêve.",
    en: "",
    words: ["בחלומי","פגשתי","זאב"],
  },
  {
    id: "l-168",
    day: 17,
    he: "יוֹרֵד גֶּשֶׁם זַלְעָפוֹת.",
    tr: "",
    fr: "Il pleut des clous.",
    en: "",
    words: ["יורד","גשם","זלעפות"],
  },
  {
    id: "l-169",
    day: 17,
    he: "תִּכָּנֵס לַחֶדֶר, בְּבַקָּשָׁה.",
    tr: "",
    fr: "Entre dans la pièce, je te prie.",
    en: "",
    words: ["תכנס","לחדר","בבקשה"],
  },
  {
    id: "l-170",
    day: 17,
    he: "שָׁמַעְתִּי שֶׁהוּא מֵת.",
    tr: "",
    fr: "J'ai entendu qu'il était mort.",
    en: "",
    words: ["שמעתי","שהוא","מת"],
  },
  {
    id: "l-171",
    day: 17,
    he: "הָאִשָּׁה הַזֹּאת עֲרֻמָּה.",
    tr: "",
    fr: "Cette femme est nue.",
    en: "",
    words: ["האשה","הזאת","ערמה"],
  },
  {
    id: "l-172",
    day: 17,
    he: "פָּשׁוּט תִּסְתַּכֵּל עָלָיו!",
    tr: "",
    fr: "Regarde-le, simplement !",
    en: "",
    words: ["פשוט","תסתכל","עליו"],
  },
  {
    id: "l-173",
    day: 17,
    he: "הַפְּלִיטִים נֶאֶבְקוּ בָּרָעָב.",
    tr: "",
    fr: "Les réfugiés se battaient contre la faim.",
    en: "",
    words: ["הפליטים","נאבקו","ברעב"],
  },
  {
    id: "l-174",
    day: 17,
    he: "סְתָם הִסְתַּכַּלְתִּי מִסָּבִיב.",
    tr: "",
    fr: "Je regardais juste aux alentours.",
    en: "",
    words: ["סתם","הסתכלתי","מסביב"],
  },
  {
    id: "l-175",
    day: 17,
    he: "עָבְרוּ אַרְבָּעִים שָׁנָה.",
    tr: "",
    fr: "Quarante ans ont passé.",
    en: "",
    words: ["עברו","ארבעים","שנה"],
  },
  {
    id: "l-176",
    day: 17,
    he: "לֶחֶם מְיֻצָּר מִקֶּמַח.",
    tr: "",
    fr: "Le pain est fait à partir de la farine.",
    en: "",
    words: ["לחם","מיצר","מקמח"],
  },
  {
    id: "l-177",
    day: 17,
    he: "לְאוֹפֶה לַחְמָנִיּוֹת מְעֻלּוֹת.",
    tr: "",
    fr: "Le boulanger a d'excellents petits pains.",
    en: "",
    words: ["לאופה","לחמניות","מעלות"],
  },
  {
    id: "l-178",
    day: 17,
    he: "הַבַּחוּרָה טָעֲמָה מֵהַלֶּחֶם.",
    tr: "",
    fr: "La femme goûte le pain.",
    en: "",
    words: ["הבחורה","טעמה","מהלחם"],
  },
  {
    id: "l-179",
    day: 18,
    he: "אָרוּר הַחוֹשֵׁב עָווֹן.",
    tr: "",
    fr: "Honi soit qui mal y pense.",
    en: "",
    words: ["ארור","החושב","עוון"],
  },
  {
    id: "l-180",
    day: 18,
    he: "הַשֶּׁמֶשׁ תִּשְׁקַע בְּקָרוֹב.",
    tr: "",
    fr: "Le soleil se couchera bientôt.",
    en: "",
    words: ["השמש","תשקע","בקרוב"],
  },
  {
    id: "l-181",
    day: 18,
    he: "אַחַת מֵהַתְּשׁוּבוֹת נְכוֹנָה.",
    tr: "",
    fr: "L'une des réponses est correcte.",
    en: "",
    words: ["אחת","מהתשובות","נכונה"],
  },
  {
    id: "l-182",
    day: 18,
    he: "אָנוּ תְּלוּיִים בְּךָ.",
    tr: "",
    fr: "Nous dépendons de vous.",
    en: "",
    words: ["אנו","תלויים","בך"],
  },
  {
    id: "l-183",
    day: 18,
    he: "סָדָאם סֵרֵב לָאוּלְטִימָטוּם.",
    tr: "",
    fr: "Saddam rejeta l'ultimatum.",
    en: "",
    words: ["סדאם","סרב","לאולטימטום"],
  },
  {
    id: "l-184",
    day: 18,
    he: "מוֹכְרִים עִתּוֹנִים בַּקִּיּוֹסְקִים.",
    tr: "",
    fr: "On vend les journaux dans un kiosque.",
    en: "",
    words: ["מוכרים","עתונים","בקיוסקים"],
  },
  {
    id: "l-185",
    day: 18,
    he: "הַמָּטוֹס נוֹחֵת בִּשְׁמוֹנֶה.",
    tr: "",
    fr: "L'avion arrive à huit heures.",
    en: "",
    words: ["המטוס","נוחת","בשמונה"],
  },
  {
    id: "l-186",
    day: 18,
    he: "דַּעְתִּי שׁוֹנָה מִשֶּׁלְּךָ.",
    tr: "",
    fr: "Mon opinion diffère de la vôtre.",
    en: "",
    words: ["דעתי","שונה","משלך"],
  },
  {
    id: "l-187",
    day: 18,
    he: "נֶהֱנֵית בִּנְסִיעָה לְלוֹנְדוֹן?",
    tr: "",
    fr: "T'es-tu amusée lors de ton voyage à Londres ?",
    en: "",
    words: ["נהנית","בנסיעה","ללונדון"],
  },
  {
    id: "l-188",
    day: 18,
    he: "לִמְתֵי מְיֹעָד הַמַּאֲמָר?",
    tr: "",
    fr: "Quand l'article est-il attendu ?",
    en: "",
    words: ["למתי","מיעד","המאמר"],
  },
  {
    id: "l-189",
    day: 18,
    he: "מָתַי הִבְחַנְתָּ בְּכָךְ?",
    tr: "",
    fr: "Quand as-tu remarqué cela ?",
    en: "",
    words: ["מתי","הבחנת","בכך"],
  },
  {
    id: "l-190",
    day: 18,
    he: "הַבִּטָּחוֹן הֻגְבַּר בָּעִיר.",
    tr: "",
    fr: "La sécurité a été renforcée dans la ville.",
    en: "",
    words: ["הבטחון","הגבר","בעיר"],
  },
  {
    id: "l-191",
    day: 19,
    he: "הַגֶּשֶׁם הִכָּה בַּחַלּוֹן.",
    tr: "",
    fr: "La pluie battait sur la fenêtre.",
    en: "",
    words: ["הגשם","הכה","בחלון"],
  },
  {
    id: "l-192",
    day: 19,
    he: "הַסִּדְרָה הַהַרְמוֹנִית מִתְבַּדֶּרֶת.",
    tr: "",
    fr: "La série harmonique diverge.",
    en: "",
    words: ["הסדרה","ההרמונית","מתבדרת"],
  },
  {
    id: "l-193",
    day: 19,
    he: "הַיֶּלֶד מְפַחֵד מֵהַחֹשֶׁךְ.",
    tr: "",
    fr: "L'enfant a peur de l'obscurité.",
    en: "",
    words: ["הילד","מפחד","מהחשך"],
  },
  {
    id: "l-194",
    day: 19,
    he: "חִיַּגְתָּ מִסְפָּר שָׁגוּי.",
    tr: "",
    fr: "Tu as composé le mauvais numéro.",
    en: "",
    words: ["חיגת","מספר","שגוי"],
  },
  {
    id: "l-195",
    day: 19,
    he: "לְשֵׁרוּתְךָ, אֲדוֹנִי הַיָּקָר!",
    tr: "",
    fr: "À votre service, cher Monsieur !",
    en: "",
    words: ["לשרותך","אדוני","היקר"],
  },
  {
    id: "l-196",
    day: 19,
    he: "הֲתֵדַע מַהִי אַהֲבָה?",
    tr: "",
    fr: "Tu sais ce qu'est l'amour ?",
    en: "",
    words: ["התדע","מהי","אהבה"],
  },
  {
    id: "l-197",
    day: 19,
    he: "הַמַּשָּׂא וּמַתָּן נִכְשַׁל.",
    tr: "",
    fr: "La négociation a échoué.",
    en: "",
    words: ["המשא","ומתן","נכשל"],
  },
  {
    id: "l-198",
    day: 19,
    he: "יָרוּ בְּתֹם בְּבוֹסְטוֹן.",
    tr: "",
    fr: "On a tiré sur Tom à Boston.",
    en: "",
    words: ["ירו","בתם","בבוסטון"],
  },
  {
    id: "l-199",
    day: 19,
    he: "הַכִּשָּׁלוֹן מוֹלִיד הַצְלָחָה.",
    tr: "",
    fr: "De l'insuccès naît le succès.",
    en: "",
    words: ["הכשלון","מוליד","הצלחה"],
  },
  {
    id: "l-200",
    day: 19,
    he: "לְתֹם שְׁלוֹשָׁה כְּלָבִים.",
    tr: "",
    fr: "Tom a trois chiens.",
    en: "",
    words: ["לתם","שלושה","כלבים"],
  },
  {
    id: "l-201",
    day: 19,
    he: "אִמָּא תָּמִיד צוֹדֶקֶת.",
    tr: "",
    fr: "Maman a toujours raison.",
    en: "",
    words: ["אמא","תמיד","צודקת"],
  },
  {
    id: "l-202",
    day: 19,
    he: "טוֹם נִפְרַד מִמֶּנִּי.",
    tr: "",
    fr: "Tom a rompu avec moi.",
    en: "",
    words: ["טום","נפרד","ממני"],
  },
  {
    id: "l-203",
    day: 20,
    he: "בְּעָיָתְךָ דּוֹמָה לְשֵׁלִי.",
    tr: "",
    fr: "Votre problème est similaire au mien.",
    en: "",
    words: ["בעיתך","דומה","לשלי"],
  },
  {
    id: "l-204",
    day: 20,
    he: "הַבֵּדוּאִים חַיִּים בַּמִּדְבָּר.",
    tr: "",
    fr: "Les Bédouins vivent dans le désert.",
    en: "",
    words: ["הבדואים","חיים","במדבר"],
  },
  {
    id: "l-205",
    day: 20,
    he: "נִשְׂתָּרְרָה שְׁתִיקָה קְצָרָה.",
    tr: "",
    fr: "Il y eut un bref silence.",
    en: "",
    words: ["נשתררה","שתיקה","קצרה"],
  },
  {
    id: "l-206",
    day: 20,
    he: "הַמַּיִם הָאֵלּוּ טְעִימִים.",
    tr: "",
    fr: "Cette eau a bon goût.",
    en: "",
    words: ["המים","האלו","טעימים"],
  },
  {
    id: "l-207",
    day: 20,
    he: "תִּבְחַר בֵּין הַשְּׁנַיִם.",
    tr: "",
    fr: "Choisis entre les deux.",
    en: "",
    words: ["תבחר","בין","השנים"],
  },
  {
    id: "l-208",
    day: 20,
    he: "בֵּיתָם מוֹדֶרְנִי מְאוֹד.",
    tr: "",
    fr: "Leur maison est très moderne.",
    en: "",
    words: ["ביתם","מודרני","מאוד"],
  },
  {
    id: "l-209",
    day: 20,
    he: "יִהְיֶה הַכּוֹחַ עִמְּךָ.",
    tr: "",
    fr: "Que la force soit avec toi.",
    en: "",
    words: ["יהיה","הכוח","עמך"],
  },
  {
    id: "l-210",
    day: 20,
    he: "הָאֱנוֹשׁוּת יְכוֹלָה לְהִשְׁתַּנּוֹת.",
    tr: "",
    fr: "L'humanité peut changer.",
    en: "",
    words: ["האנושות","יכולה","להשתנות"],
  },
  {
    id: "l-211",
    day: 20,
    he: "הַמַּלְכָּה חַיֶּבֶת לָמוּת.",
    tr: "",
    fr: "La reine doit mourir.",
    en: "",
    words: ["המלכה","חיבת","למות"],
  },
  {
    id: "l-212",
    day: 20,
    he: "חַיֵּי שְׁחֹרִים חֲשׁוּבִים.",
    tr: "",
    fr: "La vie des Noirs compte.",
    en: "",
    words: ["חיי","שחרים","חשובים"],
  },
  {
    id: "l-213",
    day: 20,
    he: "אֵלֶן יְהוּדִי צָרְפָתִי.",
    tr: "",
    fr: "Alain est un Juif français.",
    en: "",
    words: ["אלן","יהודי","צרפתי"],
  },
  {
    id: "l-214",
    day: 20,
    he: "הַתַּלְמִידִים פָּרְצוּ בִּצְחוֹק.",
    tr: "",
    fr: "Les élèves ont éclaté de rire.",
    en: "",
    words: ["התלמידים","פרצו","בצחוק"],
  },
  {
    id: "l-215",
    day: 22,
    he: "הַיַּלְדָּה הַקְּטַנָּה יֻשַּׁנְתְּ.",
    tr: "",
    fr: "La petite fille dort.",
    en: "",
    words: ["הילדה","הקטנה","ישנת"],
  },
  {
    id: "l-216",
    day: 22,
    he: "טְרוֹלִינְג זִוַּתִּי אָמָּנוּת.",
    tr: "",
    fr: "Troller est une art.",
    en: "",
    words: ["טרולינג","זותי","אמנות"],
  },
  {
    id: "l-217",
    day: 22,
    he: "מָרִי נָהֲגָה בָּאוֹטוֹ.",
    tr: "",
    fr: "Marie conduisait la voiture.",
    en: "",
    words: ["מרי","נהגה","באוטו"],
  },
  {
    id: "l-218",
    day: 22,
    he: "יָרַד שֶׁלֶג בִּירוּשָׁלַיִם.",
    tr: "",
    fr: "Il neigeait à Jérusalem.",
    en: "",
    words: ["ירד","שלג","בירושלים"],
  },
  {
    id: "l-219",
    day: 22,
    he: "עֲתִידְךָ מַתְחִיל הַיּוֹם.",
    tr: "",
    fr: "Ton avenir commence aujourd'hui.",
    en: "",
    words: ["עתידך","מתחיל","היום"],
  },
  {
    id: "l-220",
    day: 22,
    he: "תָּפַסְנוּ חֵלֶק מֵהַטֵּרוֹרִיסְטִים.",
    tr: "",
    fr: "Nous avons capturé certains des terroristes.",
    en: "",
    words: ["תפסנו","חלק","מהטרוריסטים"],
  },
  {
    id: "l-221",
    day: 22,
    he: "תַּאֲוָה גּוֹרֶמֶת לְסֵבֶל.",
    tr: "",
    fr: "La passion crée de la souffrance.",
    en: "",
    words: ["תאוה","גורמת","לסבל"],
  },
  {
    id: "l-222",
    day: 22,
    he: "קאבילים, כָּתְבוּ בְּקַבִּילִית!",
    tr: "",
    fr: "Ô Kabyles, écrivez le kabyle.",
    en: "",
    words: ["קאבילים","כתבו","בקבילית"],
  },
  {
    id: "l-223",
    day: 22,
    he: "כַּדּוּר הָאָרֶץ חוֹלֶה.",
    tr: "",
    fr: "La terre est malade.",
    en: "",
    words: ["כדור","הארץ","חולה"],
  },
  {
    id: "l-224",
    day: 22,
    he: "כֻּלָּנוּ נִהְיֵינוּ קוֹמוּנִיסְטִים.",
    tr: "",
    fr: "Nous sommes tous devenus communistes.",
    en: "",
    words: ["כלנו","נהיינו","קומוניסטים"],
  },
  {
    id: "l-225",
    day: 22,
    he: "אִשְׁתִּי מִתְקַשָּׁה לְהֵרָדֵם.",
    tr: "",
    fr: "Ma femme a des difficultés à s'endormir.",
    en: "",
    words: ["אשתי","מתקשה","להרדם"],
  },
  {
    id: "l-226",
    day: 22,
    he: "הָאֵם דָּאֲגָה לִילָדֶיהָ.",
    tr: "",
    fr: "La mère se faisait du souci pour ses enfants.",
    en: "",
    words: ["האם","דאגה","לילדיה"],
  },
  {
    id: "l-227",
    day: 23,
    he: "הַמִּקְלֶדֶת הַזּוֹ מֻשְׁלֶמֶת.",
    tr: "",
    fr: "Ce clavier est parfait.",
    en: "",
    words: ["המקלדת","הזו","משלמת"],
  },
  {
    id: "l-228",
    day: 23,
    he: "יָגַעְתִּי תְּקוּפָה מְמֻשֶּׁכֶת.",
    tr: "",
    fr: "J'ai longtemps peiné.",
    en: "",
    words: ["יגעתי","תקופה","ממשכת"],
  },
  {
    id: "l-229",
    day: 23,
    he: "לַדֹּב זָנָב קָצָר.",
    tr: "",
    fr: "L'ours a une courte queue.",
    en: "",
    words: ["לדב","זנב","קצר"],
  },
  {
    id: "l-230",
    day: 23,
    he: "לַסּוּס אַרְבַּע רַגְלַיִם.",
    tr: "",
    fr: "Le cheval a quatre pieds.",
    en: "",
    words: ["לסוס","ארבע","רגלים"],
  },
  {
    id: "l-231",
    day: 23,
    he: "צִמְחוֹנִים אוֹכְלִים יְרָקוֹת.",
    tr: "",
    fr: "Les végétariens mangent des légumes.",
    en: "",
    words: ["צמחונים","אוכלים","ירקות"],
  },
  {
    id: "l-232",
    day: 23,
    he: "רָקַדְנוּ עַד חֲצוֹת.",
    tr: "",
    fr: "On a dansé jusqu'à minuit.",
    en: "",
    words: ["רקדנו","עד","חצות"],
  },
  {
    id: "l-233",
    day: 23,
    he: "אֱמוּנָה תָּזִיז הָרִים.",
    tr: "",
    fr: "La foi transporte les montagnes.",
    en: "",
    words: ["אמונה","תזיז","הרים"],
  },
  {
    id: "l-234",
    day: 23,
    he: "פִּילִים מִשְׁתַּמְּשִׁים בַּכֵּלִים.",
    tr: "",
    fr: "Les éléphants utilisent des outils.",
    en: "",
    words: ["פילים","משתמשים","בכלים"],
  },
  {
    id: "l-235",
    day: 23,
    he: "טָטָרִי, דָּבָר טָטָרִית!",
    tr: "",
    fr: "Tatar, parle tatar !",
    en: "",
    words: ["טטרי","דבר","טטרית"],
  },
  {
    id: "l-236",
    day: 23,
    he: "בְּלִי עַיִן הָרָע.",
    tr: "",
    fr: "Mashallah.",
    en: "",
    words: ["בלי","עין","הרע"],
  },
  {
    id: "l-237",
    day: 23,
    he: "עֵדֶר הַגִּ'ירָפוֹת בָּרַח.",
    tr: "",
    fr: "Le troupeau de girafes s'est enfui.",
    en: "",
    words: ["עדר","הגירפות","ברח"],
  },
  {
    id: "l-238",
    day: 23,
    he: "תִּתְנַהֲגִי כְּמוֹ מְבֻגֶּרֶת.",
    tr: "",
    fr: "Sois un adulte.",
    en: "",
    words: ["תתנהגי","כמו","מבגרת"],
  },
  {
    id: "l-239",
    day: 24,
    he: "תֵּימָן נִמְצֵאת בְּמִלְחָמָה.",
    tr: "",
    fr: "Le Yémen est en guerre.",
    en: "",
    words: ["תימן","נמצאת","במלחמה"],
  },
  {
    id: "l-240",
    day: 24,
    he: "שְׁתֵּינוּ רוֹצוֹת כַּרְטִיסִים.",
    tr: "",
    fr: "Nous voulons toutes les deux des billets.",
    en: "",
    words: ["שתינו","רוצות","כרטיסים"],
  },
  {
    id: "l-241",
    day: 24,
    he: "טִפּוּלֵי הֲמָרָה הוֹרְגִים.",
    tr: "",
    fr: "La thérapie de conversion tue.",
    en: "",
    words: ["טפולי","המרה","הורגים"],
  },
  {
    id: "l-242",
    day: 24,
    he: "חַיֶּיךָ עַכְשָׁו, תִּבְכֶּה אַחַר-כָּךְ!",
    tr: "",
    fr: "Souris maintenant, pleure plus tard !",
    en: "",
    words: ["חייך","עכשו","תבכה","אחרכך"],
  },
  {
    id: "l-243",
    day: 24,
    he: "לֵךְ לָרוֹפֵא לָקַחַת מִרְשָׁם!",
    tr: "",
    fr: "Va voir un docteur pour te faire faire une ordonnance.",
    en: "",
    words: ["לך","לרופא","לקחת","מרשם"],
  },
  {
    id: "l-244",
    day: 24,
    he: "הַכַּרְטִיס הַזֶּה תָּקֵף לְחֹדֶשׁ.",
    tr: "",
    fr: "Ce billet est valable un mois.",
    en: "",
    words: ["הכרטיס","הזה","תקף","לחדש"],
  },
  {
    id: "l-245",
    day: 24,
    he: "רָאִיתִי אוֹתָם נִכְנָסִים לַבַּנְק.",
    tr: "",
    fr: "Je les ai vus entrer dans la banque.",
    en: "",
    words: ["ראיתי","אותם","נכנסים","לבנק"],
  },
  {
    id: "l-246",
    day: 24,
    he: "מָה שְׁלוֹם הַהוֹרִים שֶׁלָּכֶם?",
    tr: "",
    fr: "Comment vont vos parents ?",
    en: "",
    words: ["מה","שלום","ההורים","שלכם"],
  },
  {
    id: "l-247",
    day: 24,
    he: "הוּא מְדַבֵּר גַּם צָרְפָתִית.",
    tr: "",
    fr: "Il parle aussi français.",
    en: "",
    words: ["הוא","מדבר","גם","צרפתית"],
  },
  {
    id: "l-248",
    day: 24,
    he: "כִּי הֵם צוֹפִים בַּטֵּלֵוִיזְיָה.",
    tr: "",
    fr: "Parce qu'elles regardent la télé.",
    en: "",
    words: ["כי","הם","צופים","בטלויזיה"],
  },
  {
    id: "l-249",
    day: 24,
    he: "הוּא בְּרֹאשׁ הַכִּתָּה בְּאַנְגְּלִית.",
    tr: "",
    fr: "Il est en tête de la classe en anglais.",
    en: "",
    words: ["הוא","בראש","הכתה","באנגלית"],
  },
  {
    id: "l-250",
    day: 24,
    he: "הוּא הִסְתַּכֵּל עָלַי וְנָבַח.",
    tr: "",
    fr: "Il me regarda et aboya.",
    en: "",
    words: ["הוא","הסתכל","עלי","ונבח"],
  },
  {
    id: "l-251",
    day: 25,
    he: "חָשַׁבְתִּי אוֹתוֹ בְּטָעוּת לְאָחִי.",
    tr: "",
    fr: "Je l'ai pris pour mon frère.",
    en: "",
    words: ["חשבתי","אותו","בטעות","לאחי"],
  },
  {
    id: "l-252",
    day: 25,
    he: "סֶנְטִימֵטֶר הוּא יְחִידַת אֹרֶךְ.",
    tr: "",
    fr: "Le centimètre est une unité de longueur.",
    en: "",
    words: ["סנטימטר","הוא","יחידת","ארך"],
  },
  {
    id: "l-253",
    day: 25,
    he: "הַאִם קַיֶּמֶת הִיסְטוֹרְיָה אוֹבְּיֶקְטִיבִית?",
    tr: "",
    fr: "L'histoire objective existe-t-elle ?",
    en: "",
    words: ["האם","קימת","היסטוריה","אוביקטיבית"],
  },
  {
    id: "l-254",
    day: 25,
    he: "הוּא הַבֵּן הַיָּחִיד שֶׁלָּהֶם.",
    tr: "",
    fr: "C'est leur fils unique.",
    en: "",
    words: ["הוא","הבן","היחיד","שלהם"],
  },
  {
    id: "l-255",
    day: 25,
    he: "תַּגִּיד מָה שֶׁאַתָּה חוֹשֵׁב.",
    tr: "",
    fr: "Dites ce que vous pensez.",
    en: "",
    words: ["תגיד","מה","שאתה","חושב"],
  },
  {
    id: "l-256",
    day: 25,
    he: "אֱמֹר מָה שֶׁעַל לִבְּךָ.",
    tr: "",
    fr: "Dites ce que vous pensez.",
    en: "",
    words: ["אמר","מה","שעל","לבך"],
  },
  {
    id: "l-257",
    day: 25,
    he: "הִיא יָלְדָה תִּינוֹק בָּרִיא.",
    tr: "",
    fr: "Elle donna naissance à un bébé en bonne santé.",
    en: "",
    words: ["היא","ילדה","תינוק","בריא"],
  },
  {
    id: "l-258",
    day: 25,
    he: "אַתֶּם מְקַבְּלִים כַּרְטִיסֵי אַשְׁרַאי?",
    tr: "",
    fr: "Acceptez-vous les cartes de crédits ?",
    en: "",
    words: ["אתם","מקבלים","כרטיסי","אשראי"],
  },
  {
    id: "l-259",
    day: 25,
    he: "קַר שָׁם, אֲפִלּוּ בַּקַּיִץ.",
    tr: "",
    fr: "Il fait froid là-bas, même l'été.",
    en: "",
    words: ["קר","שם","אפלו","בקיץ"],
  },
  {
    id: "l-260",
    day: 25,
    he: "הַמִּלָּה הַזֹּאת מַגִּיעָה מִיְּוָנִית.",
    tr: "",
    fr: "Ce mot vient du grec.",
    en: "",
    words: ["המלה","הזאת","מגיעה","מיונית"],
  },
  {
    id: "l-261",
    day: 25,
    he: "הוּא לִפְעָמִים מִתְעַצְבֵּן לְחִנָּם",
    tr: "",
    fr: "Il se met parfois en colère pour rien.",
    en: "",
    words: ["הוא","לפעמים","מתעצבן","לחנם"],
  },
  {
    id: "l-262",
    day: 25,
    he: "זֹאת מְכוֹנָה מְאֹד מֻרְכֶּבֶת.",
    tr: "",
    fr: "C'est une machine très complexe.",
    en: "",
    words: ["זאת","מכונה","מאד","מרכבת"],
  },
  {
    id: "l-263",
    day: 26,
    he: "הוּא יָכוֹל לְדַבֵּר יַפָּנִית.",
    tr: "",
    fr: "Il peut parler japonais.",
    en: "",
    words: ["הוא","יכול","לדבר","יפנית"],
  },
  {
    id: "l-264",
    day: 26,
    he: "הִשְׁאַרְתִּי בַּבַּיִת מַתָּנָה עֲבוּרָהּ.",
    tr: "",
    fr: "J'avais laissé un cadeau pour elle à la maison.",
    en: "",
    words: ["השארתי","בבית","מתנה","עבורה"],
  },
  {
    id: "l-265",
    day: 26,
    he: "כָּל הַמּוֹשָׁבִים הָיוּ תְּפוּסִים.",
    tr: "",
    fr: "Toutes les chaises étaient occupées.",
    en: "",
    words: ["כל","המושבים","היו","תפוסים"],
  },
  {
    id: "l-266",
    day: 26,
    he: "הוּא גִּלָּה סַבְלָנוּת רַבָּה.",
    tr: "",
    fr: "Il était très patient.",
    en: "",
    words: ["הוא","גלה","סבלנות","רבה"],
  },
  {
    id: "l-267",
    day: 26,
    he: "זֶה הַסֵּפֶר שֶׁאַתְּ מְחַפֶּשֶׂת.",
    tr: "",
    fr: "C'est le livre que vous cherchez.",
    en: "",
    words: ["זה","הספר","שאת","מחפשת"],
  },
  {
    id: "l-268",
    day: 26,
    he: "הַמְּחִירִים הוּזְלוּ לֹא מִזְּמַן.",
    tr: "",
    fr: "Les prix ont baissé récemment.",
    en: "",
    words: ["המחירים","הוזלו","לא","מזמן"],
  },
  {
    id: "l-269",
    day: 26,
    he: "הַסְּפָרִים זְמִינִים עַכְשָׁו לְכֻלָּם.",
    tr: "",
    fr: "Les livres sont maintenant accessibles à tout le monde.",
    en: "",
    words: ["הספרים","זמינים","עכשו","לכלם"],
  },
  {
    id: "l-270",
    day: 26,
    he: "הַדְּבוֹרָה נָחֲתָה עַל הַפֶּרַח.",
    tr: "",
    fr: "L'abeille a atterri sur la fleur.",
    en: "",
    words: ["הדבורה","נחתה","על","הפרח"],
  },
  {
    id: "l-271",
    day: 26,
    he: "חַיָּלִים הָרְגוּ כַּפְרִיִּים רַבִּים.",
    tr: "",
    fr: "Beaucoup de villageois ont été tués par des soldats.",
    en: "",
    words: ["חילים","הרגו","כפריים","רבים"],
  },
  {
    id: "l-272",
    day: 26,
    he: "סִין גְּדוֹלָה יוֹתֵר מִיַּפָּן.",
    tr: "",
    fr: "La Chine est plus grande que le Japon.",
    en: "",
    words: ["סין","גדולה","יותר","מיפן"],
  },
  {
    id: "l-273",
    day: 26,
    he: "נוּכַל לְהִשְׁתַּמֵּשׁ בַּמַּעְבָּדָה הַלְּשׁוֹנִית?",
    tr: "",
    fr: "Pouvons-nous utiliser le laboratoire de langues ?",
    en: "",
    words: ["נוכל","להשתמש","במעבדה","הלשונית"],
  },
  {
    id: "l-274",
    day: 26,
    he: "זֶה דּוּ-שִׂיחַ שֶׁל חֵרְשִׁים.",
    tr: "",
    fr: "C'est un dialogue de sourds.",
    en: "",
    words: ["זה","דושיח","של","חרשים"],
  },
  {
    id: "l-275",
    day: 27,
    he: "הוּא הֶחְלִיט לַהֲפֹךְ לַטַּיָּס.",
    tr: "",
    fr: "Il a décidé de devenir pilote.",
    en: "",
    words: ["הוא","החליט","להפך","לטיס"],
  },
  {
    id: "l-276",
    day: 27,
    he: "אַתְּ חוֹשֶׁבֶת שֶׁזֶּה יַעֲבֹד?",
    tr: "",
    fr: "Penses-tu que cela fonctionnera ?",
    en: "",
    words: ["את","חושבת","שזה","יעבד"],
  },
  {
    id: "l-277",
    day: 27,
    he: "חֲבֵרִים, הִגִּיעַ הַזְּמַן שֶׁאֵלֵךְ.",
    tr: "",
    fr: "Les amis, il est temps que j'y aille.",
    en: "",
    words: ["חברים","הגיע","הזמן","שאלך"],
  },
  {
    id: "l-278",
    day: 27,
    he: "הַשָּׁעָה שְׁתַּיִם אַחַר הַצָּהֳרַיִם.",
    tr: "",
    fr: "Il est deux heures de l'après-midi.",
    en: "",
    words: ["השעה","שתים","אחר","הצהרים"],
  },
  {
    id: "l-279",
    day: 27,
    he: "הִיא פָּנְתָה שְׂמֹאלָה בַּפִּנָּה.",
    tr: "",
    fr: "Elle a tourné à gauche à l'angle.",
    en: "",
    words: ["היא","פנתה","שמאלה","בפנה"],
  },
  {
    id: "l-280",
    day: 27,
    he: "אֶפְשָׁר לְהָבִין אֶת כַּעֲסוֹ.",
    tr: "",
    fr: "Sa colère est compréhensible.",
    en: "",
    words: ["אפשר","להבין","את","כעסו"],
  },
];

export const linesForDay = (day: number) => LINES.filter((l) => l.day === day);
export const LAST_SEEDED_DAY = 27;
