/**
 * Seed corpus — Days 1 to 5.
 *
 * Generated from the sentences already authored in deck.ts: the §6 patterns
 * and the example frames attached to function words. The full corpus follows
 * the pipeline in PROGRAMME.md §13; this exists so the programme can issue
 * real assignments before that lands.
 *
 * Do not hand-edit. Regenerate, or replace wholesale when the corpus arrives.
 */

import type { Line } from "./programme.ts";

export const LINES: Line[] = [
  {
    id: "l-001",
    day: 1,
    he: "?אֵיפֹה הַ___",
    tr: "Eifo ha-___?",
    fr: "Où est le/la ___ ?",
    en: "Where is the ___?",
    words: ["p-eifo"],
    pattern: "p-eifo",
  },
  {
    id: "l-002",
    day: 1,
    he: "___ אֲנִי צָרִיךְ",
    tr: "Ani tsarich ___",
    fr: "J'ai besoin de ___",
    en: "I need ___",
    words: ["p-tsarich"],
    pattern: "p-tsarich",
  },
  {
    id: "l-003",
    day: 1,
    he: "___ אֲנִי רוֹצֶה",
    tr: "Ani rotse ___",
    fr: "Je veux ___",
    en: "I want ___",
    words: ["p-rotse"],
    pattern: "p-rotse",
  },
  {
    id: "l-004",
    day: 1,
    he: "?כַּמָּה זֶה עוֹלֶה",
    tr: "Kama ze ole?",
    fr: "Combien ça coûte ?",
    en: "How much does it cost?",
    words: ["p-kama"],
    pattern: "p-kama",
  },
  {
    id: "l-005",
    day: 1,
    he: "?אֶפְשָׁר",
    tr: "Efshar?",
    fr: "C'est possible ? / Je peux ?",
    en: "Is it possible? / May I?",
    words: ["p-efshar"],
    pattern: "p-efshar",
  },
  {
    id: "l-006",
    day: 1,
    he: "___ יֵשׁ לִי",
    tr: "Yesh li ___",
    fr: "J'ai ___",
    en: "I have ___",
    words: ["p-yesh-li"],
    pattern: "p-yesh-li",
  },
  {
    id: "l-007",
    day: 1,
    he: "אֲנִי לֹא מֵבִין",
    tr: "Ani lo mevin",
    fr: "Je ne comprends pas",
    en: "I don't understand",
    words: ["p-lo-mevin"],
    pattern: "p-lo-mevin",
  },
  {
    id: "l-008",
    day: 1,
    he: "?מָה זֶה",
    tr: "Ma ze?",
    fr: "Qu'est-ce que c'est ?",
    en: "What is this?",
    words: ["p-ma-ze"],
    pattern: "p-ma-ze",
  },
  {
    id: "l-009",
    day: 1,
    he: "?אַתָּה מְדַבֵּר אַנְגְּלִית",
    tr: "Ata medaber anglit?",
    fr: "Tu parles anglais ?",
    en: "Do you speak English?",
    words: ["p-anglit"],
    pattern: "p-anglit",
  },
  {
    id: "l-010",
    day: 1,
    he: "אֲנִי רוֹצֶה קָפֶה",
    tr: "Ani rotse kafe",
    fr: "Je veux un café",
    en: "I want a coffee",
    words: ["w-ani"],
  },
  {
    id: "l-011",
    day: 1,
    he: "הוּא לוֹמֵד",
    tr: "Hu lomed",
    fr: "Il apprend",
    en: "He is learning",
    words: ["w-hu-hi"],
  },
  {
    id: "l-012",
    day: 1,
    he: "אֲנַחְנוּ הוֹלְכִים",
    tr: "Anachnu holchim",
    fr: "Nous allons",
    en: "We are going",
    words: ["w-anachnu"],
  },
  {
    id: "l-013",
    day: 2,
    he: "?אַתֶּם מְדַבְּרִים עִבְרִית",
    tr: "Atem medabrim ivrit?",
    fr: "Vous parlez hébreu ?",
    en: "Do you speak Hebrew?",
    words: ["w-atem-hem"],
  },
  {
    id: "l-014",
    day: 2,
    he: "?מִי זֶה",
    tr: "Mi ze?",
    fr: "Qui est-ce ?",
    en: "Who is that?",
    words: ["w-mi"],
  },
  {
    id: "l-015",
    day: 2,
    he: "?אֵיפֹה הַתַּחֲנָה",
    tr: "Eifo ha-tachana?",
    fr: "Où est la gare ?",
    en: "Where is the station?",
    words: ["w-eifo"],
  },
  {
    id: "l-016",
    day: 2,
    he: "?מָתַי זֶה",
    tr: "Matai ze?",
    fr: "C'est quand ?",
    en: "When is it?",
    words: ["w-matai"],
  },
  {
    id: "l-017",
    day: 2,
    he: "?לָמָּה לֹא",
    tr: "Lama lo?",
    fr: "Pourquoi pas ?",
    en: "Why not?",
    words: ["w-lama"],
  },
  {
    id: "l-018",
    day: 2,
    he: "?אֵיךְ אוֹמְרִים",
    tr: "Eich omrim?",
    fr: "Comment dit-on ?",
    en: "How do you say?",
    words: ["w-eich"],
  },
  {
    id: "l-019",
    day: 2,
    he: "?מֵאַיִן אַתָּה",
    tr: "Me'ayin ata?",
    fr: "D'où viens-tu ?",
    en: "Where are you from?",
    words: ["w-meayin"],
  },
  {
    id: "l-020",
    day: 2,
    he: "יֵשׁ לִי זְמַן",
    tr: "Yesh li zman",
    fr: "J'ai du temps",
    en: "I have time",
    words: ["w-yesh-ein"],
  },
  {
    id: "l-021",
    day: 2,
    he: "אֲנִי צָרִיךְ עֶזְרָה",
    tr: "Ani tsarich ezra",
    fr: "J'ai besoin d'aide",
    en: "I need help",
    words: ["w-tsarich"],
  },
  {
    id: "l-022",
    day: 2,
    he: "אֲנִי יָכוֹל",
    tr: "Ani yachol",
    fr: "Je peux",
    en: "I can",
    words: ["w-yachol"],
  },
  {
    id: "l-023",
    day: 2,
    he: "אֲנִי הוֹלֵךְ הַבַּיְתָה",
    tr: "Ani holech habaita",
    fr: "Je rentre à la maison",
    en: "I'm going home",
    words: ["w-holech"],
  },
  {
    id: "l-024",
    day: 2,
    he: "?אַתָּה בָּא",
    tr: "Ata ba?",
    fr: "Tu viens ?",
    en: "Are you coming?",
    words: ["w-ba"],
  },
  {
    id: "l-025",
    day: 3,
    he: "אֲנִי לֹא יוֹדֵעַ",
    tr: "Ani lo yode'a",
    fr: "Je ne sais pas",
    en: "I don't know",
    words: ["w-yodea"],
  },
  {
    id: "l-026",
    day: 3,
    he: "?אֵיפֹה אַתָּה גָּר",
    tr: "Eifo ata gar?",
    fr: "Où habites-tu ?",
    en: "Where do you live?",
    words: ["w-gar"],
  },
  {
    id: "l-027",
    day: 3,
    he: "אֲנִי עוֹבֵד",
    tr: "Ani oved",
    fr: "Je travaille",
    en: "I work",
    words: ["w-oved"],
  },
  {
    id: "l-028",
    day: 3,
    he: "אֲנִי לוֹמֵד עִבְרִית",
    tr: "Ani lomed ivrit",
    fr: "J'apprends l'hébreu",
    en: "I'm learning Hebrew",
    words: ["w-lomed"],
  },
  {
    id: "l-029",
    day: 3,
    he: "אֲנִי מְדַבֵּר קְצָת",
    tr: "Ani medaber ktsat",
    fr: "Je parle un peu",
    en: "I speak a little",
    words: ["w-medaber"],
  },
  {
    id: "l-030",
    day: 3,
    he: "קָפֶה וְעוּגָה",
    tr: "Kafe ve-uga",
    fr: "Un café et un gâteau",
    en: "Coffee and cake",
    words: ["w-ve"],
  },
  {
    id: "l-031",
    day: 3,
    he: "אֲנִי רוֹצֶה אֲבָל אֵין לִי זְמַן",
    tr: "Ani rotse aval ein li zman",
    fr: "Je veux mais je n'ai pas le temps",
    en: "I want to but I have no time",
    words: ["w-aval"],
  },
  {
    id: "l-032",
    day: 3,
    he: "גַּם אֲנִי",
    tr: "Gam ani",
    fr: "Moi aussi",
    en: "Me too",
    words: ["w-gam"],
  },
  {
    id: "l-033",
    day: 3,
    he: "כֵּן, בְּבַקָּשָׁה",
    tr: "Ken, bevakasha",
    fr: "Oui, s'il te plaît",
    en: "Yes, please",
    words: ["w-ken-lo"],
  },
  {
    id: "l-034",
    day: 3,
    he: "קָפֶה בְּלִי סֻכָּר",
    tr: "Kafe bli sukar",
    fr: "Un café sans sucre",
    en: "Coffee without sugar",
    words: ["w-im-bli"],
  },
  {
    id: "l-035",
    day: 3,
    he: "כִּי אֲנִי לוֹמֵד",
    tr: "Ki ani lomed",
    fr: "Parce que j'apprends",
    en: "Because I'm learning",
    words: ["w-ki"],
  },
  {
    id: "l-036",
    day: 3,
    he: "הַיּוֹם אֲנִי עוֹבֵד",
    tr: "Hayom ani oved",
    fr: "Aujourd'hui je travaille",
    en: "Today I'm working",
    words: ["w-hayom"],
  },
  {
    id: "l-037",
    day: 4,
    he: "אֲנִי מְדַבֵּר קְצָת עִבְרִית",
    tr: "Ani medaber ktsat ivrit",
    fr: "Je parle un peu hébreu",
    en: "I speak a little Hebrew",
    words: ["i-ktsat"],
  },
  {
    id: "l-038",
    day: 4,
    he: "?מָה הַשֵּׁם שֶׁלְּךָ",
    tr: "Ma ha-shem shelcha?",
    fr: "Comment tu t'appelles ?",
    en: "What's your name?",
    words: ["i-ma-hashem"],
  },
  {
    id: "l-039",
    day: 4,
    he: "___ שְׁמִי",
    tr: "Shmi ___",
    fr: "Je m'appelle ___",
    en: "My name is ___",
    words: ["i-shmi"],
  },
  {
    id: "l-040",
    day: 4,
    he: "נָעִים מְאוֹד",
    tr: "na'im me'od",
    fr: "enchanté",
    en: "nice to meet you",
    words: ["i-naim"],
  },
  {
    id: "l-041",
    day: 4,
    he: "?מָה שְׁלוֹמְךָ",
    tr: "Ma shlomcha?",
    fr: "Comment vas-tu ?",
    en: "How are you?",
    words: ["i-ma-shlomcha"],
  },
  {
    id: "l-042",
    day: 4,
    he: "?מָה נִשְׁמָע",
    tr: "Ma nishma?",
    fr: "Quoi de neuf ?",
    en: "What's up?",
    words: ["i-ma-nishma"],
  },
  {
    id: "l-043",
    day: 4,
    he: "___ אֲנִי מִ",
    tr: "Ani mi-___",
    fr: "Je viens de ___",
    en: "I'm from ___",
    words: ["i-ani-mi"],
  },
  {
    id: "l-044",
    day: 4,
    he: "?בֶּן כַּמָּה אַתָּה",
    tr: "Ben kama ata?",
    fr: "Quel âge as-tu ?",
    en: "How old are you?",
    words: ["i-ben-kama"],
  },
  {
    id: "l-045",
    day: 4,
    he: "עוֹלֶה חָדָשׁ",
    tr: "oleh chadash",
    fr: "nouvel immigrant",
    en: "new immigrant",
    words: ["i-oleh"],
  },
  {
    id: "l-046",
    day: 4,
    he: "יֵשׁ לִי שְׁנֵי יְלָדִים",
    tr: "Yesh li shnei yeladim",
    fr: "J'ai deux enfants",
    en: "I have two children",
    words: ["f-yesh-li-yeladim"],
  },
  {
    id: "l-047",
    day: 4,
    he: "___ אֲנִי גָּר בְּ",
    tr: "Ani gar be-___",
    fr: "J'habite à ___",
    en: "I live in ___",
    words: ["h-gar-be"],
  },
  {
    id: "l-048",
    day: 4,
    he: "לִפְנוֹת יָמִינָה",
    tr: "Lifnot yamina",
    fr: "Tourner à droite",
    en: "Turn right",
    words: ["d-yamina"],
  },
  {
    id: "l-049",
    day: 5,
    he: "לִפְנוֹת שְׂמֹאלָה",
    tr: "Lifnot smola",
    fr: "Tourner à gauche",
    en: "Turn left",
    words: ["d-smola"],
  },
  {
    id: "l-050",
    day: 5,
    he: "תֵּלֵךְ יָשָׁר",
    tr: "Telech yashar",
    fr: "Va tout droit",
    en: "Go straight",
    words: ["d-yashar"],
  },
  {
    id: "l-051",
    day: 5,
    he: "?זֶה קָרוֹב",
    tr: "Ze karov?",
    fr: "C'est près ?",
    en: "Is it near?",
    words: ["d-karov"],
  },
  {
    id: "l-052",
    day: 5,
    he: "זֶה רָחוֹק מִכָּאן",
    tr: "Ze rachok mikan",
    fr: "C'est loin d'ici",
    en: "It's far from here",
    words: ["d-rachok"],
  },
  {
    id: "l-053",
    day: 5,
    he: "אֲנִי כָּאן",
    tr: "Ani kan",
    fr: "Je suis ici",
    en: "I'm here",
    words: ["d-kan"],
  },
  {
    id: "l-054",
    day: 5,
    he: "זֶה שָׁם",
    tr: "Ze sham",
    fr: "C'est là-bas",
    en: "It's over there",
    words: ["d-sham"],
  },
  {
    id: "l-055",
    day: 5,
    he: "לְיַד הַתַּחֲנָה",
    tr: "Leyad ha-tachana",
    fr: "À côté de la gare",
    en: "Next to the station",
    words: ["d-leyad"],
  },
  {
    id: "l-056",
    day: 5,
    he: "מוּל הַבַּיִת",
    tr: "Mul ha-bayit",
    fr: "En face de la maison",
    en: "Opposite the house",
    words: ["d-mul"],
  },
  {
    id: "l-057",
    day: 5,
    he: "בֵּין הַבַּיִת וְהַתַּחֲנָה",
    tr: "Bein ha-bayit ve-ha-tachana",
    fr: "Entre la maison et la gare",
    en: "Between the house and the station",
    words: ["d-bein"],
  },
  {
    id: "l-058",
    day: 5,
    he: "?___ אֵיךְ מַגִּיעִים לְ",
    tr: "Eich magi'im le-___?",
    fr: "Comment on va à ___ ?",
    en: "How do you get to ___?",
    words: ["d-eich-magiim"],
  },
];

export const linesForDay = (day: number) => LINES.filter((l) => l.day === day);
export const LAST_SEEDED_DAY = 5;
