/**
 * Assessment passages, one per month. Generated — do not hand-edit.
 *
 * Tatoeba sentences (CC-BY) that appear nowhere in the corpus, vocalised by
 * Dicta Nakdan. Regenerate with scripts/build-passages.mjs, which re-checks
 * the exclusion against the current lines.
 *
 * These are separate sentences on a shared subject, not continuous prose.
 */

import type { Passage } from "./passages.ts";

export const PASSAGES: Passage[] = [
  {
    month: 1,
    sentences: [
      { he: "תַּעֲשֶׂה מַשֶּׁהוּ!", fr: "Fais quelque chose !" },
      { he: "אֲנִי יָכוֹל לַעֲזֹר לְךָ?", fr: "Puis-je vous aider ?" },
      { he: "אֲנִי יְכוֹלָה לַעֲזֹר לְךָ?", fr: "Puis-je vous aider ?" },
      { he: "מָה אַתָּה?", fr: "T'es quoi ?" },
      { he: "מָה אַתְּ?", fr: "T'es quoi ?" },
      { he: "אַתָּה בָּטוּחַ?", fr: "Es-tu sûr ?" },
      { he: "אַתָּה מְדַבֵּר אִיטַלְקִית?", fr: "Parlez-vous italien ?" },
      { he: "אַתְּ מְדַבֶּרֶת אִיטַלְקִית?", fr: "Parlez-vous italien ?" },
      { he: "אַתָּה מְדַבֵּר עִבְרִית?", fr: "Est-ce que tu parles l'hébreu ?" },
      { he: "כָּל הַסְּפָרִים הָאֵלֶּה שֶׁלִּי.", fr: "Tous ces livres sont les miens." },
      { he: "מָה קָרָה?", fr: "Qu'est-ce qui s'est passé ?" },
      { he: "אַתְּ נְשׂוּאָה?", fr: "Es-tu mariée ?" },
      { he: "תֵּן לוֹ זְמַן.", fr: "Donne-lui du temps." },
      { he: "תֵּן לָהּ זְמַן.", fr: "Donne-lui du temps." },
      { he: "תְּנִי לוֹ זְמַן.", fr: "Donne-lui du temps." },
      { he: "תְּנִי לָהּ זְמַן.", fr: "Donne-lui du temps." },
      { he: "יֵשׁ לְךָ מַשֶּׁהוּ לְהַצְהִיר?", fr: "Avez-vous quelque chose à déclarer ?" },
      { he: "אֲנִי אוֹהֵב אוֹתְךָ.", fr: "Je t'adore." },
      { he: "אֲנִי אוֹהֶבֶת אוֹתְךָ.", fr: "Je t'adore." },
      { he: "לֹא מֵבִין.", fr: "Je ne comprends pas." },
      { he: "לְאָן אַתָּה הוֹלֵךְ?", fr: "Où allez-vous ?" },
      { he: "מִי שָׁבַר אֶת הַחַלּוֹן?", fr: "Qui a cassé la fenêtre ?" },
      { he: "לֵךְ תִּזְדַּיֵּן!", fr: "Casse-toi." },
      { he: "עָלֶיךָ לָלֶכֶת לְשָׁם מִיָּד.", fr: "Il faut que tu y ailles tout de suite." },
      { he: "יֵשׁ לְךָ כַּמָּה סְפָרִים.", fr: "Vous avez quelques livres." },
      { he: "אֲנִי לֹא מְדַבֵּר גֶּרְמָנִית.", fr: "Je ne sais pas parler allemand." },
      { he: "אֲנִי לֹא מְדַבֶּרֶת גֶּרְמָנִית.", fr: "Je ne sais pas parler allemand." },
      { he: "הוּא הָלַךְ.", fr: "Il s'en alla." },
      { he: "אֵיפֹה הָיִיתָ?", fr: "Où étais-tu ?" },
      { he: "כָּתוּב אֶת שִׁמְךָ כָּאן.", fr: "Écrivez votre nom ici." },
    ],
  },
  {
    month: 2,
    sentences: [
      { he: "אַתָּה חוֹשֵׁב יוֹתֵר מִדַּי.", fr: "Tu penses trop." },
      { he: "אִבַּדְתִּי אֶת הָעִפָּרוֹן שֶׁלִּי.", fr: "J'ai perdu mon crayon." },
      { he: "אַחֲרֵי הַמָּוֶת, הָרוֹפֵא.", fr: "Après la mort, le docteur." },
      { he: "יָרְדוּ גְּשָׁמִים עַזִּים.", fr: "Il a fortement plu." },
      { he: "זֶה מֵרִיחַ טוֹב!", fr: "Ça sent bon !" },
      { he: "הָיוּ לָנוּ שְׁלוֹשָׁה מְטוֹסִים.", fr: "Nous avions trois avions." },
      { he: "מָה אַתָּה רוֹצֶה לֶאֱכֹל?", fr: "Que veux-tu manger ?" },
      { he: "מָה אַתְּ רוֹצָה לֶאֱכֹל?", fr: "Que veux-tu manger ?" },
      { he: "אֲנִי חוֹשֵׁב שֶׁיִּהְיֶה חַם הַיּוֹם.", fr: "Je pense qu'il fera chaud aujourd'hui." },
      { he: "מָה דַּעְתְּךָ עַל עוֹד קָפֶה?", fr: "Que diriez-vous de plus de café ?" },
      { he: "אֵיךְ מֶזֶג הָאֲוִיר שָׁם?", fr: "Comment est le temps là-bas ?" },
      { he: "אֲנִי צָרִיךְ לָלֶכֶת לִישֹׁן.", fr: "Je dois aller dormir." },
      { he: "הוּא אוֹהֵב קָפֶה בְּלִי סֻכָּר.", fr: "Il aime son café sans sucre." },
      { he: "הָיָה קַר אֶתְמוֹל.", fr: "Il faisait froid hier." },
      { he: "עוֹד אֶפְשָׁר לִרְאוֹת אֶת הָאֳנִיָּה.", fr: "On peut encore voir le bateau." },
      { he: "אֶפְשָׁר עֲדַיִן לִרְאוֹת אֶת הָאֳנִיָּה.", fr: "On peut encore voir le bateau." },
      { he: "מָתַי תַּגִּיעַ הָרַכֶּבֶת שֶׁלּוֹ לְקִיוֹטוֹ?", fr: "Quand est-ce que son train arrive à Kyoto ?" },
      { he: "הַלֶּחֶם הַזֶּה הוּא מַעֲדָן.", fr: "Ce pain est délicieux." },
      { he: "הַלֶּחֶם הַזֶּה טָעִים.", fr: "Ce pain est délicieux." },
      { he: "אַתָּה אוֹכֵל בַּבַּיִת, אוֹ בַּחוּץ?", fr: "Est-ce que tu manges à la maison ou est-ce que tu manges dehors ?" },
      { he: "אַתְּ אוֹכֶלֶת בַּבַּיִת, אוֹ בַּחוּץ?", fr: "Est-ce que tu manges à la maison ou est-ce que tu manges dehors ?" },
      { he: "קָשֶׁה לִי בְּמָתֵמָטִיקָה.", fr: "Les mathématiques sont difficiles pour moi." },
    ],
  },
  {
    month: 3,
    sentences: [
      { he: "הָעֲבוֹדָה הַזֹּאת הִיא מֵעֵבֶר לְכִשּׁוּרַי.", fr: "Ce travail dépasse ma compétence." },
      { he: "הָעֲבוֹדָה הַזֹּאת הִיא מֵעֵבֶר לִיכוֹלוֹתַי.", fr: "Ce travail dépasse ma compétence." },
      { he: "הוּא אָמַר שֶׁהוּא הָיָה מְאֻשָּׁר מְאוֹד.", fr: "Il a dit qu'il était très heureux." },
      { he: "הָיִיתִי רוֹצֶה לִקְנוֹת מַצְלֵמָה כְּמוֹ זוֹ.", fr: "J'aimerais acheter une caméra comme celle-ci." },
      { he: "לַמְרוֹת כָּל הַצְלָחָתוֹ, הוּא לֹא מְאֻשָּׁר.", fr: "Malgré tout son succès, il n'est pas heureux." },
      { he: "אֲנִי לֹא זָקוּק לָרַחֲמִים שֶׁלְּךָ.", fr: "Je n'ai pas besoin de ta pitié." },
      { he: "רֹב הָאֲנָשִׁים אוֹהֲבִים לִצְפּוֹת בַּטֵּלֵוִיזְיָה.", fr: "La plupart des gens aiment regarder la telé." },
      { he: "הָעֵט הַזֶּה שַׁיָּךְ לִי.", fr: "Ce stylo m'appartient." },
      { he: "אֲנִי רוֹצֶה לַעֲזֹר לְךָ בְּשִׁעוּרֵי הַבַּיִת.", fr: "Je voudrais t'aider avec tes devoirs." },
      { he: "הוּא רָגִיל לַעֲבוֹדָה קָשָׁה.", fr: "Il est habitué au travail pénible." },
      { he: "אֲנִי שָׂמֵחַ לִשְׁמֹעַ אֶת הַחֲדָשׁוֹת הָאֵלֶּה.", fr: "Je suis heureux d'entendre ces nouvelles." },
      { he: "אֲנִי שְׂמֵחָה לִשְׁמֹעַ אֶת הַחֲדָשׁוֹת הָאֵלֶּה.", fr: "Je suis heureux d'entendre ces nouvelles." },
      { he: "עָבַדְתִּי קָשֶׁה, יוֹם אַחַר יוֹם.", fr: "J'ai travaillé dur, jour après jour." },
      { he: "תַּעֲמִיד אוֹתוֹ עַל הַשֻּׁלְחָן.", fr: "Pose-le sur la table." },
      { he: "תַּעֲמִיד אוֹתָהּ עַל הַשֻּׁלְחָן.", fr: "Pose-le sur la table." },
      { he: "תַּעֲמִיד אֶת זֶה עַל הַשֻּׁלְחָן.", fr: "Pose-le sur la table." },
      { he: "אֲנִי לֹא עָיֵף כָּרֶגַע.", fr: "Je ne suis pas fatigué en ce moment." },
      { he: "אֲנִי לֹא עֲיֵפָה כָּרֶגַע.", fr: "Je ne suis pas fatigué en ce moment." },
    ],
  },
  {
    month: 4,
    sentences: [
      { he: "אֲנִי לֹא יָכוֹל לִסְבֹּל אֶת הַכְּאֵב הַזֶּה.", fr: "Je ne peux pas supporter cette douleur." },
      { he: "אֲנִי לֹא יְכוֹלָה לִסְבֹּל אֶת הַכְּאֵב הַזֶּה.", fr: "Je ne peux pas supporter cette douleur." },
      { he: "הֱיוֹת שֶׁהָיִיתִי עָיֵף, הָלַכְתִּי לִישֹׁן.", fr: "Comme j'étais fatigué, je suis allé au lit." },
      { he: "מַעֲצִיב אוֹתִי לִשְׁמֹעַ אֶת זֶה.", fr: "Ça me rend triste d'entendre ça." },
      { he: "אֲנִי מַרְגִּישׁ קְצָת חַלָּשׁ הַיּוֹם.", fr: "Je me sens un peu faible aujourd'hui." },
      { he: "אֲנִי מַרְגִּישָׁה קְצָת חַלָּשָׁה הַיּוֹם.", fr: "Je me sens un peu faible aujourd'hui." },
      { he: "אֲנִי אוֹהֵב כָּל דָּבָר שֶׁהוּא יָפֶה.", fr: "J'aime tout ce qui est joli." },
      { he: "אֲנִי אוֹהֶבֶת כָּל דָּבָר שֶׁהוּא יָפֶה.", fr: "J'aime tout ce qui est joli." },
      { he: "אֲנִי רוֹצֶה לְדַבֵּר עַל אֲהוּבָתִי.", fr: "Je veux parler de mon amour." },
      { he: "אֲנִי רוֹצֶה לְדַבֵּר עַל אֲהוּבִי.", fr: "Je veux parler de mon amour." },
      { he: "אֲנִי רוֹצֶה לְדַבֵּר עַל אַהֲבָתִי.", fr: "Je veux parler de mon amour." },
      { he: "הוּא כָּתַב לִי מִכְתַּב אַהֲבָה.", fr: "Il m'a écrit une lettre d'amour." },
      { he: "לֹא בִּשְׁבִיל זֶה אֲנִי נִמְצָא כָּאן.", fr: "Ce n'est pas pour cela que je suis là." },
      { he: "כֻּלָּם הָיוּ עַל סַף דְּמָעוֹת.", fr: "Tous étaient au bord des larmes." },
      { he: "אֶת הָאֹשֶׁר אִי אֶפְשָׁר לִקְנוֹת.", fr: "Le bonheur ne s'achète pas." },
      { he: "יֵשׁ לִי מַשֶּׁהוּ שֶׁאֲנִי חַיָּב לְהַגִּיד לְךָ.", fr: "J'ai quelque chose que je veux te dire." },
    ],
  },
  {
    month: 5,
    sentences: [
      { he: "אַתָּה יָכוֹל לְזַהוֹת אֶת הַבֵּן אָדָם בַּתְּמוּנָה?", fr: "Est-ce que vous reconnaissez l'homme sur cette photo ?" },
      { he: "לֹא הָיְתָה לִי כָּל כַּוָּנָה לִפְגֹּעַ בְּךָ.", fr: "Je ne te voulais aucun mal." },
      { he: "אֵינֶנִּי יוֹדֵעַ מָתַי הוּא יָבוֹא לְכָאן.", fr: "Je ne sais pas quand il viendra ici." },
      { he: "הוּא יוֹצֵא לִנְיוּ יוֹרְק בַּשָּׁבוּעַ הַבָּא.", fr: "Il part pour New York la semaine prochaine." },
      { he: "הוּא טָס לִנְיוּ יוֹרְק בַּשָּׁבוּעַ הַבָּא.", fr: "Il part pour New York la semaine prochaine." },
      { he: "אֵיפֹה אֲנִי יָכוֹל לִמְצֹא מִשְׁחַת שִׁנַּיִם?", fr: "Où puis-je trouver du dentifrice ?" },
      { he: "אֵיפֹה אֲנִי יְכוֹלָה לִמְצֹא מִשְׁחַת שִׁנַּיִם?", fr: "Où puis-je trouver du dentifrice ?" },
      { he: "אַף אֶחָד לֹא שָׂם לֵב אֵלָיו.", fr: "Personne ne lui prêtait attention." },
      { he: "אַף אֶחָד לֹא שָׂם לֵב אֵלֶיהָ.", fr: "Personne ne lui prêtait attention." },
      { he: "אַל תִּקְרָא סְפָרִים בְּחֶדֶר אַפְלוּלִי כָּל כָּךְ.", fr: "Tu ne devrais pas lire de livres dans une pièce si peu éclairée." },
      { he: "אַף פַּעַם לֹא רָאִיתִי כֶּלֶב גָּדוֹל כָּל כָּךְ.", fr: "Je n'ai jamais vu de chien aussi gros." },
      { he: "אֲנִי לֹא רוֹאֶה שׁוּם סִבָּה לְהִתְנַצֵּל.", fr: "Je ne vois aucune raison pour laquelle je devrais m'excuser." },
      { he: "אֲנִי לֹא רוֹאֶה כָּל סִבָּה לְהִתְנַצֵּל.", fr: "Je ne vois aucune raison pour laquelle je devrais m'excuser." },
      { he: "הִיא הֶחְוִירָה לְשֵׁמַע הַחֲדָשׁוֹת הָרָעוֹת הָאֵלֶּה.", fr: "Elle pâlit à ces mauvaises nouvelles." },
    ],
  },
];
