/**
 * The reading library. Generated — do not hand-edit.
 *
 * Tatoeba sentences (CC-BY) vocalised by Dicta Nakdan, chosen so that none
 * appears in the programme corpus or in an assessment passage. Regenerate with
 * scripts/build-reading.mjs, which re-checks those exclusions.
 */

import type { Passage } from "./reading.ts";

export const LIBRARY: Passage[] = [
  {
    id: "r01",
    level: 1,
    theme: "general",
    words: 56,
    sentences: [
      { he: "בְּבַקָּשָׁה תַּחֲשֹׁב עַל זֶה.", fr: "Penses-y." },
      { he: "תַּחֲשֹׁב עַל זֶה.", fr: "Pensez-y." },
      { he: "לֹא לָלֶכֶת עַל הַדֶּשֶׁא.", fr: "Ne marchez pas sur la pelouse." },
      { he: "בַּתְּמוּנָה כֻּלָּם מְחַיְּכִים.", fr: "Tout le monde sourit sur la photographie." },
      { he: "הָאַהֲבָה הִיא, מִטִּבְעָהּ, עִוֶּרֶת.", fr: "L'amour rend aveugle." },
      { he: "אֲנִי מְתַכְנֵן לְהִשָּׁאֵר בָּעִיר.", fr: "Je vais rester dans cette ville." },
      { he: "כִּי הֵם צוֹפִים בַּטֵּלֵוִיזְיָה.", fr: "Parce qu'elles regardent la télé." },
      { he: "אֵין לָנוּ אוֹתָם עֲרָכִים.", fr: "Nous n'avons pas les mêmes valeurs." },
      { he: "גִּלָּה כְּגִילִי.", fr: "Elle est aussi jeune que moi." },
      { he: "הִיא צְעִירָה כָּמוֹנִי.", fr: "Elle est aussi jeune que moi." },
      { he: "הוּא מְסֻגָּל לָרוּץ.", fr: "Il est capable de courir." },
      { he: "יֵשׁ לְךָ אַרְבָּעָה כְּלָבִים.", fr: "Tu as quatre chiens." },
      { he: "אַתָּה צָרִיךְ אֶת עֶזְרָתֵנוּ?", fr: "As-tu besoin de notre aide ?" },
      { he: "אַתְּ צְרִיכָה אֶת עֶזְרָתֵנוּ?", fr: "As-tu besoin de notre aide ?" },
      { he: "אַתָּה מַכִּיר אוֹתָם?", fr: "Les connaissez-vous ?" },
      { he: "אַתְּ מַכִּירָה אוֹתָם?", fr: "Les connaissez-vous ?" },
    ],
  },
  {
    id: "r02",
    level: 1,
    theme: "emotion",
    words: 55,
    sentences: [
      { he: "הוּא הָיָה אַמִּיץ.", fr: "Il était brave." },
      { he: "הִיא מְאֻשֶּׁרֶת.", fr: "Elle est heureuse." },
      { he: "הִתְרַשַּׁמְתִּי מְאוֹד.", fr: "Je suis très impressionné." },
      { he: "מַהוּ הָאֹשֶׁר?", fr: "Qu'est-ce que c'est le bonheur ?" },
      { he: "אֲנִי שָׂמֵחַ", fr: "Je suis heureux." },
      { he: "אֹשֶׁר הוּא בְּרִיאוּת.", fr: "Le bonheur c'est la santé." },
      { he: "הַמִּכְתָּב הֶעֱצִיב אוֹתָהּ.", fr: "La lettre la rendit triste." },
      { he: "הוּא עֲדַיִן כּוֹעֵס.", fr: "Il est encore fâché." },
      { he: "אֲנִי מְפֻנָּק.", fr: "Je suis gâté." },
      { he: "אֲנִי מַרְגִּישׁ שֶׁעוֹקְבִים אַחֲרֵי.", fr: "Je me sens surveillé." },
      { he: "הוּא הָיָה עָיֵף מְאוֹד.", fr: "Il était très fatigué." },
      { he: "לִבִּי חָדַל לִפְעֹם.", fr: "Mon cœur s'est arrêté de battre." },
      { he: "אֲנִי תָּמִיד בְּלַחַץ.", fr: "Je suis toujours sous pression." },
      { he: "הָיִיתִי עָיֵף מְאוֹד הַיּוֹם.", fr: "J'étais très fatigué aujourd'hui." },
      { he: "הוּא שׁוּם דָּבָר בִּשְׁבִילִי.", fr: "Pour moi il n'est rien." },
      { he: "כַּמָּה חֲבָל!", fr: "Quel dommage !" },
      { he: "לָמָּה אַתָּה פּוֹחֵד?", fr: "Pourquoi as-tu peur ?" },
      { he: "מַדּוּעַ אַתְּ חוֹשֶׁשֶׁת?", fr: "Pourquoi as-tu peur ?" },
      { he: "אֲנַחְנוּ תָּמִיד מְקַוִּים.", fr: "Nous espérons toujours." },
    ],
  },
  {
    id: "r03",
    level: 1,
    theme: "describing",
    words: 56,
    sentences: [
      { he: "תַּקְטִין אֶת זֶה.", fr: "Rendez-le plus petit." },
      { he: "תַּקְטִינִי אֶת זֶה.", fr: "Rendez-le plus petit." },
      { he: "יְהִי אוֹר!", fr: "Que la lumière soit !" },
      { he: "זֶה זָהָב טָהוֹר.", fr: "C'est de l'or pur." },
      { he: "הָאִשָּׁה הַיָּפָה הִיא נֶחְמָדָה.", fr: "La belle femme est gentille." },
      { he: "חָשַׁבְתִּי שֶׁהַטּוּר הַזֶּה מְעַנְיֵן.", fr: "J'ai trouvé cette colonne intéressante." },
      { he: "הַטִּירָה יָפֶה.", fr: "Le château est beau." },
      { he: "הָעוֹר שֶׁלָּהּ עָדִין.", fr: "Sa peau est douce." },
      { he: "בֶּן כַּמָּה הָעֵץ הַזֶּה?", fr: "Cet arbre a quel âge ?" },
      { he: "הוֹ! זֶה לֹא יָקָר!", fr: "Waou ! C'est pas cher !" },
      { he: "אֵיזֶה רַעֲיוֹן טוֹב!", fr: "Quelle bonne idée !" },
      { he: "אֲנִי אוֹהֵב אֶת הַטִּירוֹת.", fr: "J'aime les châteaux." },
      { he: "זֶה סֶרֶט טוֹב.", fr: "C'est un bon film." },
      { he: "הָעֲנִיבָה יָפֶה מְאֹד.", fr: "La cravate est très belle." },
      { he: "רָצִיתִי נַעֲלַיִם אֲדֻמּוֹת.", fr: "Je voulais des chaussures rouges." },
      { he: "עַל מָה אַתָּה מִסְתַּכֵּל?", fr: "Que regardes-tu ?" },
      { he: "עַל מָה אַתְּ מִסְתַּכֶּלֶת?", fr: "Que regardes-tu ?" },
    ],
  },
  {
    id: "r04",
    level: 1,
    theme: "weather",
    words: 55,
    sentences: [
      { he: "הוּא הִצְטַנֵּן.", fr: "Il a attrapé froid." },
      { he: "קַר הַיּוֹם!", fr: "Il fait froid aujourd'hui !" },
      { he: "הָאַקְלִים מִשְׁתַּנֶּה.", fr: "Le climat change." },
      { he: "חֹם הוֹפֵךְ קֶרַח לְמַיִם.", fr: "La chaleur transforme la glace en eau." },
      { he: "מְעֻנָּן הַיּוֹם.", fr: "C'est nuageux aujourd'hui." },
      { he: "מָחָר יִהְיֶה מְעֻנָּן.", fr: "Ce sera nuageux demain." },
      { he: "יֵרֵד שֶׁלֶג.", fr: "Il a neigé." },
      { he: "לָבֶטַח יֵרֵד גֶּשֶׁם.", fr: "Il va certainement pleuvoir." },
      { he: "הַגֶּשֶׁם הִכָּה בַּחַלּוֹן.", fr: "La pluie battait sur la fenêtre." },
      { he: "הַצִּפּוֹר בַּשָּׁמַיִם.", fr: "L'oiseau est dans le ciel." },
      { he: "קַר מְאוֹד כָּאן.", fr: "Il fait très froid ici." },
      { he: "הַיּוֹם יִהְיֶה חַם.", fr: "Il fera chaud aujourd'hui." },
      { he: "יִהְיֶה חַם הַיּוֹם.", fr: "Il fera chaud aujourd'hui." },
      { he: "הַאִם יוֹרֵד עַכְשָׁו גֶּשֶׁם?", fr: "Pleut-il maintenant ?" },
      { he: "יוֹרֵד שֶׁלֶג.", fr: "Il neige." },
      { he: "אֲנִי אוֹהֶבֶת שֶׁלֶג.", fr: "J'aime la neige." },
      { he: "אֲנִי אוֹהֵב שֶׁלֶג.", fr: "J'aime la neige." },
      { he: "תֹּם אוֹהֵב שֶׁלֶג.", fr: "Tom aime la neige." },
      { he: "אֲנִי אוֹהֵב חֹרֶף.", fr: "J'aime l'hiver." },
      { he: "אֲנִי צָרִיךְ קֶרַח.", fr: "J'ai besoin de glace." },
    ],
  },
  {
    id: "r05",
    level: 2,
    theme: "greeting",
    words: 71,
    sentences: [
      { he: "אֲנִי רוֹצֶה שֶׁתָּשִׁיר לִי שִׁיר.", fr: "Je veux que tu chantes une chanson." },
      { he: "אֵין לִי מָה לַעֲשׂוֹת כָּרֶגַע.", fr: "Je n'ai rien à faire pour l'instant." },
      { he: "אֵין לִי מָה לַעֲשׂוֹת עַכְשָׁו.", fr: "Je n'ai rien à faire pour l'instant." },
      { he: "הִנֵּה הַכֶּלֶב שֶׁלְּךָ. וְאֵיפֹה שֶׁלִּי?", fr: "Voici ton chien. Où est le mien ?" },
      { he: "זוֹהִי הַפַּעַם הָאַחֲרוֹנָה.", fr: "Ça c'est la dernière fois." },
      { he: "שִׂים לֵב, כִּי יִהְיוּ קְשָׁיִים.", fr: "Fais attention, car il y aura des difficultés." },
      { he: "אֲנִי חוֹזֵר מִיָּד.", fr: "Je reviens tout de suite." },
      { he: "אֲנִי חוֹזֶרֶת מִיָּד.", fr: "Je reviens tout de suite." },
      { he: "הֵיי, אַתָּה! מָה אַתָּה עוֹשֶׂה?", fr: "Hé, vous ! Qu'est-ce que vous faites ?" },
      { he: "הַי, אַתֶּם! מָה אַתֶּם עוֹשִׂים?", fr: "Hé, vous ! Qu'est-ce que vous faites ?" },
      { he: "הֵיי, אַתְּ! מָה אַתְּ עוֹשָׂה?", fr: "Hé, vous ! Qu'est-ce que vous faites ?" },
      { he: "אַתָּה צָרִיךְ לָלֶכֶת.", fr: "Il faut que tu t'en ailles." },
      { he: "אַתְּ צְרִיכָה לָלֶכֶת.", fr: "Il faut que tu t'en ailles." },
      { he: "בְּסֵדֶר. מָה אֲנִי אָשִׁיר?", fr: "D'accord. Je chante quoi ?" },
      { he: "בְּסֵדֶר. אֶת מָה אָשִׁיר?", fr: "D'accord. Je chante quoi ?" },
      { he: "טוֹב. מָה אָשִׁיר?", fr: "D'accord. Je chante quoi ?" },
      { he: "פָּגַשְׁתִּי אֶת כְּרִיסְטִין כָּאן אֶתְמוֹל.", fr: "J'ai rencontré Christine ici hier." },
    ],
  },
  {
    id: "r06",
    level: 2,
    theme: "home",
    words: 74,
    sentences: [
      { he: "אֲנִי גָּר בַּבַּיִת הַזֶּה לְבַדִּי.", fr: "J'habite cette maison seul." },
      { he: "כְּבָר נִקִּיתָ אֶת הַחֶדֶר שֶׁלְּךָ?", fr: "As-tu déjà nettoyé ta chambre ?" },
      { he: "כַּמָּה עוֹלָה הַסַּפָּה הַזֹּאת?", fr: "Combien coûte ce sofa ?" },
      { he: "אַתָּה נִשְׁאָר בַּבַּיִת?", fr: "Tu restes à la maison ?" },
      { he: "אַתְּ נִשְׁאֶרֶת בַּבַּיִת?", fr: "Tu restes à la maison ?" },
      { he: "אַל תִּשְׁכְּחִי לִנְעֹל אֶת הַדֶּלֶת.", fr: "N'oublie pas de fermer la porte à clé." },
      { he: "אַל תִּשְׁכַּח לִנְעֹל אֶת הַדֶּלֶת.", fr: "N'oublie pas de fermer la porte à clé." },
      { he: "הוּא נִכְנַס לְחַדְרִי.", fr: "Il est entré dans ma chambre." },
      { he: "הוּא נִכְנַס לַחֶדֶר שֶׁלִּי.", fr: "Il est entré dans ma chambre." },
      { he: "יֵשׁ לָכֶם חֶדֶר פָּחוֹת יָקָר?", fr: "Avez-vous une chambre moins chère ?" },
      { he: "בַּחֶדֶר שֶׁלִּי יֵשׁ רַדְיוֹ.", fr: "Dans ma chambre, il y a une radio." },
      { he: "רָאִיתִי אוֹתָהּ מְנַקָּה אֶת הַחֶדֶר.", fr: "Je l'ai vue nettoyer la chambre." },
      { he: "הוּא מַרְגִּישׁ בַּבַּיִת.", fr: "Il se sent chez lui." },
      { he: "הָיָה עָלָיו לְסַדֵּר אֶת חַדְרוֹ.", fr: "Il devait ranger sa chambre." },
      { he: "סְגֹר אֶת הַדֶּלֶת כְּשֶׁתֵּצֵא מֵהַחֶדֶר.", fr: "Fermez la porte derrière vous quand vous quittez la pièce." },
      { he: "סִגְרִי אֶת הַדֶּלֶת כְּשֶׁתֵּצְאִי מֵהַחֶדֶר.", fr: "Fermez la porte derrière vous quand vous quittez la pièce." },
      { he: "סָגְרוּ אֶת הַדֶּלֶת כְּשֶׁתֵּצְאוּ מֵהַחֶדֶר.", fr: "Fermez la porte derrière vous quand vous quittez la pièce." },
    ],
  },
  {
    id: "r07",
    level: 2,
    theme: "general",
    words: 72,
    sentences: [
      { he: "הוּא שׁוֹטֵף אֶת הָאוֹטוֹ שֶׁלּוֹ.", fr: "Il lave sa voiture." },
      { he: "הֵם הִגִּיעוּ לִבְרִיטַנְיָה לִפְנֵי שָׁבוּעַ.", fr: "Ils sont arrivés en Angleterre il y a une semaine." },
      { he: "הוּא מְלַמֵּד אֶת חֲבֵרָיו אַנְגְּלִית.", fr: "Il enseigne l'anglais à ses amis." },
      { he: "הִיא נָאִיבִית בְּצוּרָה שֶׁלֹּא תֵּאָמֵן.", fr: "Elle est incroyablement naïve." },
      { he: "גַּם עַל הַמַּאְדִּים יֵשׁ חֲתוּלִים.", fr: "Il y a des chats sur Mars, également." },
      { he: "זֶה קָרָה מַמָּשׁ לָאַחֲרוֹנָה.", fr: "C'est arrivé tout récemment." },
      { he: "זֶה אֵרַע מַמָּשׁ לָאַחֲרוֹנָה.", fr: "C'est arrivé tout récemment." },
      { he: "הַאִם כְּבָר רָאִיתָ לִוְיָתָן?", fr: "As-tu déjà vu une baleine ?" },
      { he: "הַאִם רָאִיתָ לִוְיָתָן אֵי פַּעַם?", fr: "As-tu déjà vu une baleine ?" },
      { he: "הוּא נִבְחַר מֵחָדָשׁ לְרֹאשׁ עִיר.", fr: "Il a été réélu maire." },
      { he: "הוּא רַב תָּמִיד עִם אִשְׁתּוֹ.", fr: "Il se dispute toujours avec sa femme." },
      { he: "הִיא קִבְּלָה אֶת הַצָּעָתוֹ בְּשִׂמְחָה.", fr: "Elle accepta sa proposition avec joie." },
      { he: "הֵם מָצְאוּ אוֹתוֹ אָשֵׁם.", fr: "Ils l'ont trouvé coupable." },
      { he: "הָיִיתִי בּוֹדֵד בִּלְעָדֶיהָ.", fr: "J'étais seul sans elle." },
      { he: "אַל תִּגַּע בְּפֶצַע.", fr: "Ne touche pas la blessure." },
      { he: "אֲנִי אוֹהֵב אֶת הַכִּסֵּא הַזֶּה.", fr: "J'aime cette chaise." },
    ],
  },
  {
    id: "r08",
    level: 2,
    theme: "general",
    words: 74,
    sentences: [
      { he: "אֲנִי אוֹהֶבֶת אֶת הַכִּסֵּא הַזֶּה.", fr: "J'aime cette chaise." },
      { he: "אֶתְמוֹל קָנִיתִי סֵפֶר.", fr: "Hier j'ai acheté un livre." },
      { he: "זֶה לֹא הַמִּקְרֶה.", fr: "Ce n'est pas le cas." },
      { he: "הוּא הִפְסִיק לְעַשֵּׁן.", fr: "Il a arrêté de fumer." },
      { he: "לֹא נִכְנַסְתִּי לִפְרָטִים.", fr: "Je ne suis pas entré dans les détails." },
      { he: "הִיא אִבְּדָה אֶת הַדֶּרֶךְ.", fr: "Elle perdit son chemin." },
      { he: "הִיא הָלְכָה לְאִבּוּד בַּדֶּרֶךְ.", fr: "Elle perdit son chemin." },
      { he: "לֹא מִתַּפְקִידִי לַחֲזוֹת אֶת הֶעָתִיד.", fr: "Il ne m'appartient pas de prédire l'avenir." },
      { he: "הַצִּפּוֹר נִמְצֵאת בַּקֵּן שֶׁלָּהּ.", fr: "L'oiseau est dans son nid." },
      { he: "כַּמָּה זְמַן זֶה נִמְשַׁךְ?", fr: "Combien de temps est-ce que ça dure ?" },
      { he: "הַיֶּלֶד תָּפַס אֶת הֶחָתוּל בִּזְנָבוֹ.", fr: "L'enfant a attrapé le chat par la queue." },
      { he: "הוּא כַּנִּרְאֶה יַגִּיעַ בְּקָרוֹב.", fr: "Il est probable qu'il arrive bientôt." },
      { he: "אֲנִי מַכִּיר אֶת שְׁמוֹ.", fr: "Je connais son nom." },
      { he: "אָבִיו חוֹזֵר תָּמִיד מְאֻחָר הַבַּיְתָה.", fr: "Son père revient toujours tard à la maison." },
      { he: "אָבִיו תָּמִיד חוֹזֵר הַבַּיְתָה מְאֻחָר.", fr: "Son père revient toujours tard à la maison." },
      { he: "הֵם כֻּלָּם יְלָדִים תְּמִימִים.", fr: "Ils sont tous des enfants innocents." },
      { he: "הַשִּׁיר הַזֶּה מֻכָּר לָנוּ.", fr: "Cette chanson nous est familière." },
      { he: "יֵשׁ מְעַט סְטוּדֶנְטִים שֶׁמְּבִינִים לָטִינִית.", fr: "Il y a peu d’étudiants qui comprennent le latin." },
    ],
  },
  {
    id: "r09",
    level: 3,
    theme: "general",
    words: 87,
    sentences: [
      { he: "עַל מַאְדִּים יֵשׁ חֲתוּלִים גַּם כֵּן.", fr: "Il y a des chats sur Mars, également." },
      { he: "אֲנִי תָּמִיד תּוֹהֶה מָה קָרָה לוֹ.", fr: "Je me demande toujours ce qu'il lui est arrivé." },
      { he: "אֲנִי תָּמִיד תּוֹהֶה מֶה עָלָה בְּגוֹרָלוֹ.", fr: "Je me demande toujours ce qu'il lui est arrivé." },
      { he: "לֹא רָאִיתִי אוֹתוֹ כְּבָר זְמַן רַב.", fr: "Il y a très longtemps que je ne l'ai vu." },
      { he: "אָמַרְתִּי לָהֶם שׁוּב לְכַבּוֹת אֶת הָרַדְיוֹ.", fr: "Je leur ai redit de mettre la radio moins fort." },
      { he: "הִיא הִגִּיעָה שָׁעָה לְאַחַר הַמּוֹעֵד שֶׁנִּקְבַּע.", fr: "Elle est venue avec une heure de retard sur l'heure convenue." },
      { he: "תֵּן לִי דַּף נְיָר.", fr: "Donnez-moi une feuille de papier." },
      { he: "סוּס יָכוֹל לִדְהֹר מַהֵר מְאֹד.", fr: "Un cheval peut courir très vite." },
      { he: "הָיִיתִי רוֹצֶה לְבַקֵּר בִּנְיוּ יוֹרְק", fr: "J'aimerais visiter New York." },
      { he: "זֹאת מְכוֹנָה מְאֹד מֻרְכֶּבֶת.", fr: "C'est une machine très complexe." },
      { he: "בַּשָּׁבוּעַ שֶׁעָבַר נֶעֶדְרוּ מֵהַקּוּרְסִים חֲמִשָּׁה תַּלְמִידִים.", fr: "La semaine dernière 5 élèves ont été absents de cours." },
      { he: "בַּשָּׁבוּעַ שֶׁעָבַר נֶעֶדְרוּ מֵהַלִּמּוּדִים חֲמִשָּׁה תַּלְמִידִים.", fr: "La semaine dernière 5 élèves ont été absents de cours." },
      { he: "הָיִיתִי רוֹצָה לִהְיוֹת עָשִׁיר כָּמוֹהוּ.", fr: "J'aimerais être aussi riche que lui." },
      { he: "זוֹ בֻּבָּה שֶׁהִיא יָצְרָה בְּמוֹ יָדֶיהָ.", fr: "C'est une poupée qu'elle a fabriquée elle-même." },
      { he: "זוֹ בֻּבָּה שֶׁהִיא הֵכִינָה בְּמוֹ יָדֶיהָ.", fr: "C'est une poupée qu'elle a fabriquée elle-même." },
      { he: "יֵשׁ לִי פַּחַד מִזּוֹחֲלִים.", fr: "J'ai horreur des reptiles." },
    ],
  },
  {
    id: "r10",
    level: 3,
    theme: "greeting",
    words: 88,
    sentences: [
      { he: "רוּץ מַהֵר, אוֹ שֶׁתְּאַחֵר לְבֵית הַסֵּפֶר.", fr: "Courez vite, ou vous serez en retard à l'école." },
      { he: "רוּצִי מַהֵר, אוֹ שֶׁתְּאַחֲרִי לְבֵית הַסֵּפֶר.", fr: "Courez vite, ou vous serez en retard à l'école." },
      { he: "רוּצוּ מַהֵר, אוֹ שֶׁתַּאַחְרוּ לְבֵית הַסֵּפֶר.", fr: "Courez vite, ou vous serez en retard à l'école." },
      { he: "כָּל מָה שֶׁאַתָּה אוֹמֵר נָכוֹן לְגַמְרֵי.", fr: "Tout ce que vous dites est parfaitement correct." },
      { he: "כָּל מָה שֶׁאַתְּ אוֹמֶרֶת נָכוֹן לְגַמְרֵי.", fr: "Tout ce que vous dites est parfaitement correct." },
      { he: "כָּל מָה שֶׁאַתֶּם אוֹמְרִים נָכוֹן לְגַמְרֵי.", fr: "Tout ce que vous dites est parfaitement correct." },
      { he: "אַתָּה יָכוֹל לְהַזְמִין לִי מוֹנִית בְּבַקָּשָׁה?", fr: "Pourras-tu m'appeler un taxi s'il te plait ?" },
      { he: "כַּמָּה זְמַן אַתָּה מַכִּיר אֶת גּ'וּדִי?", fr: "Depuis combien de temps connais-tu Judy ?" },
      { he: "כַּמָּה זְמַן אַתְּ מַכִּירָה אֶת גּ'וּדִי?", fr: "Depuis combien de temps connais-tu Judy ?" },
      { he: "אֲנִי מוֹדֶה לְךָ מֵרֹאשׁ עַל עֶזְרָתְךָ.", fr: "Je te remercie d'avance pour ton aide." },
      { he: "תַּפְסִיק לְדַבֵּר בְּקוֹל רָם.", fr: "Arrête de parler fort." },
      { he: "הַפְסֵק לְדַבֵּר בְּקוֹל רָם.", fr: "Arrête de parler fort." },
      { he: "הַפְסִיקִי לְדַבֵּר בְּקוֹל רָם.", fr: "Arrête de parler fort." },
      { he: "תַּפְסִיקִי לְדַבֵּר בְּקוֹל רָם.", fr: "Arrête de parler fort." },
      { he: "אַרְאֶה אוֹתְךָ מְאֻחָר יוֹתֵר.", fr: "Je te verrai plus tard." },
      { he: "אֲנִי מְסָרֵב לְדַבֵּר אִתָּךְ!", fr: "Je refuse de te parler !" },
      { he: "אֲנִי מְסָרֶבֶת לְדַבֵּר אִתָּךְ!", fr: "Je refuse de te parler !" },
    ],
  },
  {
    id: "r11",
    level: 3,
    theme: "transport",
    words: 88,
    sentences: [
      { he: "בַּשָּׁעָה הַזֹּאת יֵשׁ תְּנוּעָה שֶׁלֹּא תֵּאָמֵן.", fr: "À cette heure il y a un trafic incroyable." },
      { he: "בַּשָּׁעָה הַזֹּאת כַּמּוּת הַתְּנוּעָה לֹא תֵּאָמֵן.", fr: "À cette heure il y a un trafic incroyable." },
      { he: "אָכִין לְךָ דֶּגֶם שֶׁל מָטוֹס.", fr: "Je vais te faire une maquette d'avion." },
      { he: "אָכִין לְךָ דֶּגֶם שֶׁל אֲוִירוֹן.", fr: "Je vais te faire une maquette d'avion." },
      { he: "לִפְעָמִים הָרַכֶּבֶת לֹא מַגִּיעָה בַּזְּמַן.", fr: "Parfois, le train n'arrive pas à l'heure." },
      { he: "אֲנַחְנוּ חַיָּבִים לִנְסֹעַ בָּאוֹטוֹבּוּס?", fr: "Devons-nous prendre le bus ?" },
      { he: "הִנֵּה כַּרְטִיס הַחֲזָרָה שֶׁלִּי.", fr: "Voilà mon billet de retour." },
      { he: "זֶה כַּרְטִיס הַחֲזָרָה שֶׁלִּי.", fr: "Voilà mon billet de retour." },
      { he: "אָחִי עוֹבֵר הַיּוֹם אֶת בְּחִינַת הַכְּנִיסָה.", fr: "Mon frère passe l'examen d'entrée aujourd'hui." },
      { he: "צָרִיךְ לָלֶכֶת לְבֵית הַסֵּפֶר.", fr: "Il faut aller à l’école." },
      { he: "עָלָיו לְקַבֵּל אֶת גּוֹרָלוֹ.", fr: "Il lui fallait accepter son destin." },
      { he: "בִּגְלַל הַשֶּׁלֶג, הָרַכֶּבֶת הִתְעַכְּבָה.", fr: "À cause de la neige, le train a été retardé." },
      { he: "מַהֵר יוֹתֵר, גָּבוֹהַּ יוֹתֵר, חָזָק יוֹתֵר.", fr: "Plus vite, plus haut, plus fort." },
      { he: "הָיָה לִי אֵיזֶה קֹשִׁי לִמְצֹא מוֹנִית.", fr: "J'ai eu quelque difficulté à trouver un taxi." },
      { he: "אֶפְשָׁר לְהַקִּיף אֶת הָאָרֶץ בְּרַכֶּבֶת.", fr: "Il est possible de contourner le pays en train." },
      { he: "עָבַרְתִּי, פָּחוֹת אוֹ יוֹתֵר, מִיל אֶחָד.", fr: "J'ai marché environ 1 mile." },
      { he: "צָעַדְתִּי פְּלוּס-מִינוּס מֵיְל אֶחָד.", fr: "J'ai marché environ 1 mile." },
      { he: "צָעַדְתִּי בִּסְבִיבוֹת מֵיְל אֶחָד.", fr: "J'ai marché environ 1 mile." },
    ],
  },
  {
    id: "r12",
    level: 3,
    theme: "health",
    words: 85,
    sentences: [
      { he: "כְּדֵי לְהָרַע אֶת הַמַּצָּב, אִשְׁתּוֹ חָלְתָה.", fr: "Pour arranger les choses, sa femme est tombée malade." },
      { he: "אֲנִי חַיָּב לָקַחַת אֶת הַתְּרוּפָה הַזֹּאת?", fr: "Dois-je prendre ce médicament ?" },
      { he: "אוֹמְרִים שֶׁהוּא רוֹפֵא טוֹב.", fr: "On dit qu'il est un bon docteur." },
      { he: "אֵיךְ אוּכַל לְהַגִּיעַ לְבֵית הַחוֹלִים בָּאוֹטוֹבּוּס?", fr: "Comment puis-je aller à l'hôpital en bus ?" },
      { he: "אֵיךְ אֶפְשָׁר לְהַגִּיעַ לְבֵית הַחוֹלִים בָּאוֹטוֹבּוּס?", fr: "Comment puis-je aller à l'hôpital en bus ?" },
      { he: "אֲנִי עוֹשֶׂה אַמְבַּטְיָה פַּעַם בְּיוֹם.", fr: "Je prends un bain par jour." },
      { he: "אֲנִי לֹא יָשֵׁן טוֹב.", fr: "Je ne dors pas bien." },
      { he: "אֲנִי לֹא יְשֵׁנָה טוֹב.", fr: "Je ne dors pas bien." },
      { he: "הַרְאֵה לִי אֵיפֹה כּוֹאֵב לְךָ.", fr: "Montrez-moi où vous avez mal." },
      { he: "אִמָּא שֶׁלִּי הָיְתָה חוֹלָה יוֹמַיִם.", fr: "Ma mère a été malade pendant deux jours." },
      { he: "אֲנִי לֹא מַשְׁתִּין הַרְבֵּה.", fr: "Je n'urine pas beaucoup." },
      { he: "הַמִּקְצוֹעַ שֶׁלּוֹ זֶה רוֹפֵא.", fr: "Il est médecin de profession." },
      { he: "אֲנִי לֹא מוֹצֵא אֶת הַמִּטְעָן שֶׁלִּי.", fr: "Je ne trouve pas mes bagages." },
      { he: "אֵין לִי אֶת הָאֶמְצָעִים.", fr: "Je n'en ai pas les moyens." },
      { he: "הִיא חָלְתָה בְּמַחֲלָה קָשָׁה.", fr: "Elle est tombée gravement malade." },
      { he: "אֲנִי לֹא מַמָּשׁ יָשֵׁן, אֲנִי מְנַמְנֵם.", fr: "Je ne dors pas vraiment, je sommeille." },
      { he: "אֲנִי לֹא מַמָּשׁ יְשֵׁנָה, אֲנִי מְנַמְנֶמֶת.", fr: "Je ne dors pas vraiment, je sommeille." },
    ],
  },
  {
    id: "r13",
    level: 4,
    theme: "general",
    words: 101,
    sentences: [
      { he: "כִּמְעַט אַף פַּעַם לֹא יוֹרֵד כָּאן גֶּשֶׁם.", fr: "Il ne pleut presque jamais, ici." },
      { he: "הוּא עָזַר לִי לְתַקֵּן אֶת הַשָּׁעוֹן שֶׁלִּי.", fr: "Il m'aida à réparer ma montre." },
      { he: "בְּמֶשֶׁךְ מֵאוֹת שָׁנִים הָיְתָה קְרָאקוֹב בִּירַת פּוֹלִין.", fr: "Durant des siècles, Cracovie fut la capitale de la Pologne." },
      { he: "קְרָאקוֹב הָיְתָה בִּירַת פּוֹלִין בְּמֶשֶׁךְ מֵאוֹת שָׁנִים.", fr: "Durant des siècles, Cracovie fut la capitale de la Pologne." },
      { he: "אֲנִי חוֹשֵׁב שֶׁהַדָּג הַזֶּה חַי בְּמַיִם מְתוּקִים", fr: "Je crois que ce poisson est un poisson d'eau douce." },
      { he: "אֲנִי לֹא מַצְלִיחַ לְהָבִין מָה הִיא רוֹצָה.", fr: "Je n'arrive pas à comprendre ce qu'elle veut." },
      { he: "יֵשׁ לִכְתֹּב אֶת כָּל הַתְּשׁוּבוֹת בְּהֶתְאֵם לַהַנְחָיוֹת.", fr: "Toutes les réponses doivent être écrites en suivant les instructions." },
      { he: "יֵשׁ לִי פַּחַד מָוֶת מִזּוֹחֲלִים.", fr: "J'ai horreur des reptiles." },
      { he: "אֲנִי חוֹשֵׁב שֶׁהוּא חַף מִפֶּשַׁע.", fr: "Je pense qu'il est innocent." },
      { he: "אֲנִי מַאֲמִין שֶׁהוּא חַף מִפֶּשַׁע.", fr: "Je pense qu'il est innocent." },
      { he: "אֲנִי מַעֲדִיף אֵיכוּת עַל פְּנֵי כַּמּוּת.", fr: "Je privilégie la qualité à la quantité." },
      { he: "אֲנִי לֹא מַכִּיר אֶת שְׁמוֹ.", fr: "Je ne connais pas son nom." },
      { he: "אֲנִי לֹא מַכִּיר אֶת שְׁמָהּ.", fr: "Je ne connais pas son nom." },
      { he: "אֲנִי לֹא יוֹדֵעַ מָה שְׁמוֹ.", fr: "Je ne connais pas son nom." },
      { he: "אֲנִי לֹא יוֹדַעַת מָה שְׁמוֹ.", fr: "Je ne connais pas son nom." },
      { he: "הוּא אוֹהֵב לִמְצֹא פְּגָמִים אֵצֶל אֲחֵרִים.", fr: "Il aime trouver des défauts chez les autres." },
      { he: "נָא לֹא לִדְרֹךְ עַל הַדֶּשֶׁא.", fr: "Interdiction de marcher sur l'herbe." },
    ],
  },
  {
    id: "r14",
    level: 4,
    theme: "weather",
    words: 104,
    sentences: [
      { he: "הָאַקְלִים כָּאן הוּא כְּמוֹ זֶה שֶׁל צָרְפַת.", fr: "Le climat ici est comme celui de la France." },
      { he: "הַחֹם הוֹפֵךְ אֶת הַקֶּרַח לְמַיִם.", fr: "La chaleur transforme la glace en eau." },
      { he: "אֲנִי אוֹהֶבֶת אֶת קוֹל הַגֶּשֶׁם עַל הַגַּג.", fr: "J'aime le son de la pluie sur le toit." },
      { he: "אֲנִי אוֹהֵב אֶת קוֹל הַגֶּשֶׁם עַל הַגַּג.", fr: "J'aime le son de la pluie sur le toit." },
      { he: "חַם פֹּה מְאֹד, לֹא כֵן?", fr: "Il fait très chaud, n'est-ce pas ?" },
      { he: "זוֹ שְׁעַת הַתַּחֲזִית שֶׁל מֶזֶג הָאֲוִיר.", fr: "C'est l'heure de la météo." },
      { he: "הַגֶּשֶׁם, הַיּוֹם, מַתְאִים לְמַצַּב הָרוּחַ שֶׁלִּי.", fr: "La pluie convient bien, aujourd'hui, à mon humeur." },
      { he: "מֵעוֹלָם לֹא רָאִיתִי שְׁקִיעָה יָפֶה כָּל כָּךְ.", fr: "Je n'avais jamais vu un aussi splendide coucher de soleil." },
      { he: "אֵינֶנִּי מְסֻגָּל יוֹתֵר לָשֵׂאת אֶת הַחֹם הַזֶּה.", fr: "Je ne peux plus supporter cette chaleur." },
      { he: "מָחָר יִהְיֶה חַם עוֹד יוֹתֵר מֵאֲשֶׁר הַיּוֹם.", fr: "Demain sera encore plus chaud qu'aujourd'hui." },
      { he: "הַגֶּשֶׁם הוֹלֵךְ בְּעִקְבוֹתַי לְכָל מָקוֹם.", fr: "La pluie me suit partout !" },
      { he: "מִלְּבַד זֹאת, מַתְחִיל לָרֶדֶת גֶּשֶׁם.", fr: "À part cela, il commence à pleuvoir." },
      { he: "לֹא יָכֹלְתִּי לָלֶכֶת לָעֲבוֹדָה, כִּי הָיִיתִי חוֹלֶה.", fr: "Je n'ai pas pu aller travailler parce que j'étais malade." },
      { he: "הַאִם אַתָּה מַגִּיעַ לְבֵית הַסֵּפֶר בָּאוֹטוֹבּוּס?", fr: "Vas-tu à l'école en autobus ?" },
      { he: "אַתְּ נוֹסַעַת לְבֵית הַסֵּפֶר בָּאוֹטוֹבּוּס?", fr: "Vas-tu à l'école en autobus ?" },
      { he: "לֹא הָיָה לוֹ אָז כֶּסֶף עָלָיו.", fr: "Il n'avait alors pas d'argent sur lui." },
      { he: "אָז לֹא הָיָה בְּאַמְתַּחְתּוֹ כֶּסֶף כְּלָל.", fr: "Il n'avait alors pas d'argent sur lui." },
    ],
  },
  {
    id: "r15",
    level: 4,
    theme: "health",
    words: 104,
    sentences: [
      { he: "אֲנִי לֹא אוֹהֵב לָצֵאת הַחוּצָה כְּשֶׁיּוֹרֵד גֶּשֶׁם.", fr: "Je n'aime pas sortir quand il pleut." },
      { he: "אֲנִי לֹא אוֹהֶבֶת לָצֵאת הַחוּצָה כְּשֶׁיּוֹרֵד גֶּשֶׁם.", fr: "Je n'aime pas sortir quand il pleut." },
      { he: "יֵשׁ לִי רֹשֶׁם שֶׁאִבַּדְתִּי אֶת הָאַרְנָק שֶׁלִּי.", fr: "J'ai l'impression d'avoir perdu mon porte-monnaie." },
      { he: "אֲנִי עָסוּק עַכְשָׁו וַאֲנִי לֹא יָכוֹל לָצֵאת.", fr: "Je suis occupé en ce moment et je ne peux pas sortir." },
      { he: "אֲנִי עֲסוּקָה כָּרֶגַע וַאֲנִי לֹא יְכוֹלָה לָצֵאת.", fr: "Je suis occupé en ce moment et je ne peux pas sortir." },
      { he: "אַתָּה חַיָּב לָלֶכֶת לִבְדִיקָה אֵצֶל הָרוֹפֵא בִּדְחִיפוּת.", fr: "Tu devrais immédiatement aller te faire examiner par le médecin." },
      { he: "אַתְּ חַיֶּבֶת לָלֶכֶת לִבְדִיקָה אֵצֶל הָרוֹפֵא בִּדְחִיפוּת.", fr: "Tu devrais immédiatement aller te faire examiner par le médecin." },
      { he: "אֲנִי לֹא יָכוֹל לִשְׁלֹט בְּכָל מָה שֶׁקּוֹרֶה.", fr: "Je ne parviens pas à contrôler ce qui se passe." },
      { he: "זֶה הָיָה כְּאֵב רֹאשׁ נוֹרָאִי.", fr: "C'était un terrible mal de tête." },
      { he: "אֲנִי לֹא יָכוֹל לְסַיֵּעַ לְךָ.", fr: "Je ne peux pas vous aider." },
      { he: "זֶה הָיָה כְּאֵב רֹאשׁ נוֹרָא.", fr: "C'était un terrible mal de tête." },
      { he: "הַבְּעָיָה שֶׁלְּךָ דּוֹמָה לְזוֹ שֶׁלִּי.", fr: "Votre problème est similaire au mien." },
      { he: "אֵין לִי כָּאן מָקוֹם שֶׁלִּי.", fr: "Je n'ai pas ma place ici." },
      { he: "אֲנִי שׂוֹנֵא אֹכֶל שֶׁל בֵּית חוֹלִים.", fr: "Je déteste la nourriture d'hôpital." },
      { he: "אֲנִי רוֹצֶה לְפוֹצֵץ לְעַצְמִי אֶת הַמּוֹחַ.", fr: "Je veux me faire sauter la cervelle." },
      { he: "הַשָּׂטָן אָמַר לִי לַעֲשׂוֹת אֶת זֶה.", fr: "C'est le diable qui me l'a ordonné." },
      { he: "הוּא חוֹשֵׁב שֶׁיֵּשׁ בְּתוֹכֵנוּ מְרַגֵּל.", fr: "Il pense qu'il y a un espion parmi nous." },
    ],
  },
  {
    id: "r16",
    level: 4,
    theme: "general",
    words: 101,
    sentences: [
      { he: "הִיא נָשְׂאָה תִּינוֹק עַל גַּבָּהּ.", fr: "Elle portait un bébé sur son dos." },
      { he: "שָׂפָה אַחַת אַף פַּעַם לֹא מַסְפִּיקָה.", fr: "Une langue ne suffit jamais." },
      { he: "הוּא אִבֵּד שְׁנֵי בָּנִים בַּמִּלְחָמָה.", fr: "Il a perdu deux fils à la guerre." },
      { he: "חֲבָל שֶׁאַתָּה נֶאֱלַץ לַעֲזֹב אֶת יַפָּן.", fr: "C'est dommage que tu quittes le Japon." },
      { he: "לְעִתִּים קְרוֹבוֹת אוֹקְטוֹבֶּרְפְּסָט מִסְתַּיֵּם כְּבָר בְּסֶפְּטֶמְבֶּר.", fr: "L'Oktoberfest se termine souvent déjà en septembre." },
      { he: "בִּלְתִּי אֶפְשָׁרִי לִחְיוֹת עַל הָאִי הַזֶּה.", fr: "Il est impossible de vivre sur cette île." },
      { he: "הִיא מְנַסָּה תָּמִיד לַעֲזֹר לַאֲנָשִׁים אֲחֵרִים.", fr: "Elle essaie toujours d'aider les autres." },
      { he: "הָיָה לִי צֹרֶךְ בְּדִיּוּק בָּזֶה.", fr: "C'est précisément cela dont j'avais besoin." },
      { he: "הִיא נוֹסַעַת לִנְיוּ יוֹרְק בְּיוֹם רִאשׁוֹן הַקָּרוֹב.", fr: "Elle part pour New-York dimanche prochain." },
      { he: "אֲנִי מְאַשֵּׁר אֶת הַמֵּיזָם שֶׁלָּהּ.", fr: "J'approuve son projet." },
      { he: "אֲנִי מְאַשֵּׁר אֶת הַמֵּיזָם שֶׁלּוֹ.", fr: "J'approuve son projet." },
      { he: "אֲנִי מְאַשֵּׁר אֶת הַפְּרוֹיֵקְט שֶׁלּוֹ.", fr: "J'approuve son projet." },
      { he: "הוּא חָטַף אֶת הַמִּכְתָּב מֵהַיָּד שֶׁלִּי.", fr: "Il m'arracha la lettre de la main." },
      { he: "הוּא רוֹצֶה לִנְסֹעַ לְאַרְצוֹת הַבְּרִית.", fr: "Il veut aller aux États-Unis d'Amérique." },
      { he: "הוּא אַף פַּעַם לֹא מְשַׁקֵּר.", fr: "Il ne ment jamais." },
      { he: "הוּא הִבְטִיחַ אַף פַּעַם לֹא לְשַׁקֵּר עוֹד.", fr: "Il a promis de ne plus jamais mentir." },
      { he: "נִכְנַסְתִּי בְּטָעוּת לְחֶדֶר שֶׁל מִישֶׁהוּ אַחֵר.", fr: "Je suis entré dans la chambre de quelqu'un d'autre par inadvertance." },
      { he: "שָׁכַחְתִּי לְהַדְבִּיק בּוּל עַל הַמַּעֲטָפָה.", fr: "J’ai oublié de mettre un timbre sur l’enveloppe." },
    ],
  },
  {
    id: "r17",
    level: 5,
    theme: "general",
    words: 119,
    sentences: [
      { he: "אֲנִי לֹא יָכוֹל עוֹד לִסְבֹּל אֶת הָרַעַשׁ הַזֶּה.", fr: "Je ne peux plus supporter ce bruit." },
      { he: "גַּם אִם מִתְבּוֹנְנִים הֵיטֵב, לֹא רוֹאִים שׁוּם דָּבָר.", fr: "Même en regardant bien on ne voit rien." },
      { he: "הוּא נָסַע לִרְאוֹת אוֹתָהּ בִּזְמַן שֶׁהִיא גָּרָה בְּלוֹנְדוֹן.", fr: "Il est allé la voir lorsqu'elle habitait à Londres." },
      { he: "כְּבָר נִמְאַס לִי לִשְׁמֹעַ אֶת כָּל הַתְּלוּנוֹת שֶׁלָּהּ.", fr: "J'en ai marre d'écouter ses plaintes." },
      { he: "כְּמוֹ לְעִתִּים קְרוֹבוֹת, הוּא נֶעְדָּר הַיּוֹם מִבֵּית הַסֵּפֶר.", fr: "Comme souvent, il était absent de l'école aujourd'hui." },
      { he: "מַר סְמִית מְמֻנֶּה עַל הַכִּתָּה הַזֹּאת.", fr: "M. Smith est chargé de cette classe." },
      { he: "יֵשׁ בַּעֲלֵי חַיִּים נְדִירִים בְּיוֹתֵר בְּאוֹסְטְרַלְיָה.", fr: "Il y a des animaux très rares en Australie." },
      { he: "יֵשׁ לָהּ אוֹתוֹ מִסְפַּר בּוּלִים כְּמוֹ לִי.", fr: "Elle a autant de timbres que moi." },
      { he: "יֵשׁ לָהּ אוֹתָהּ כַּמּוּת בּוּלִים כְּמוֹ לִי.", fr: "Elle a autant de timbres que moi." },
      { he: "לֹא יָכוֹל לִהְיוֹת שֶׁהוּא קָרָא אֶת הַסֵּפֶר.", fr: "Il ne peut pas avoir lu ce livre." },
      { he: "הָיוּ לוֹ שְׁלוֹשָׁה בָּנִים, שֶׁהָפְכוּ לְעוֹרְכֵי דִּין.", fr: "Il avait trois fils qui devinrent avocats." },
      { he: "קִבַּלְתִּי אֶת חֲתִימָתוֹ שֶׁל זַמָּר מְפֻרְסָם.", fr: "J'ai eu l'autographe d'un chanteur célèbre." },
      { he: "אֲנִי לֹא יוֹדֵעַ בְּוַדָּאוּת מָתַי הוּא יָבוֹא.", fr: "Je ne sais pas avec certitude quand il viendra." },
      { he: "אֲנִי לֹא יוֹדַעַת בְּבִטָּחוֹן מָתַי הוּא יָבוֹא.", fr: "Je ne sais pas avec certitude quand il viendra." },
      { he: "הוּא שִׁנָּה אֶת גִּישָׁתוֹ בְּאֹפֶן פִּתְאוֹמִי.", fr: "Il changea d'attitude brusquement." },
      { he: "תֵּן אֶת זֶה לְמִישֶׁהוּ שֶׁזָּקוּק לָזֶה.", fr: "Donne-le à quelqu'un qui en a besoin." },
      { he: "הוּא הִגִּיעַ מֻקְדָּם כַּאֲשֶׁר בִּקְּשׁוּ זֹאת מִמֶּנּוּ.", fr: "Il venait tôt quand on le lui demandait." },
    ],
  },
  {
    id: "r18",
    level: 5,
    theme: "emotion",
    words: 117,
    sentences: [
      { he: "אֲנִי כָּל כָּךְ עָיֵף, שֶׁאֲנִי לֹא יָכוֹל לִלְמֹד.", fr: "Je suis si fatigué que je ne peux pas étudier." },
      { he: "אֲנִי לֹא יוֹדֵעַ מָה לוֹמַר כְּדֵי לְנַחֵם אוֹתְךָ.", fr: "Je ne sais pas quoi dire pour te consoler." },
      { he: "אֲנִי לֹא יוֹדַעַת מָה לוֹמַר כְּדֵי לְנַחֵם אוֹתְךָ.", fr: "Je ne sais pas quoi dire pour te consoler." },
      { he: "זֶה לֹא מוּזָר, לְדַעְתֵּךְ, שֶׁאֲנִי צְרִיכָה לִחְיוֹת לְבַד?", fr: "Tu ne trouves pas ça bizarre que je doive vivre seul ?" },
      { he: "זֶה לֹא מוּזָר, לְדַעְתֵּךְ, שֶׁאֲנִי צָרִיךְ לִחְיוֹת לְבַד?", fr: "Tu ne trouves pas ça bizarre que je doive vivre seul ?" },
      { he: "אֲנִי מִצְטַעֶרֶת עַל כָּל מָה שֶׁגָּרַמְתִּי לָךְ.", fr: "Je suis désolée pour tout ce que je vous ai causé." },
      { he: "אֲנִי רוֹצֶה לַעֲשׂוֹת אִתּוֹ יַחֲסֵי מִין.", fr: "Je veux faire l'amour avec lui." },
      { he: "אַתָּה תַּרְגִּישׁ כְּמוֹ הָאָדָם הֲכִי מְאֻשָּׁר בָּעוֹלָם.", fr: "Vous vous sentirez la personne la plus heureuse au monde." },
      { he: "אֲנִי חוֹשֵׁב שֶׁאֶצְטָרֵף אֲלֵיכֶם, אֲבָל לֹא הֶחְלַטְתִּי עֲדַיִן.", fr: "Je pense que je me joindrai à vous, mais je n'ai pas encore décidé." },
      { he: "אִם מְדַבְּרִים עַל שָׂפוֹת זָרוֹת, אַתָּה מְדַבֵּר צָרְפָתִית?", fr: "En parlant de langues étrangères, parlez-vous français ?" },
      { he: "בְּבַקָּשָׁה הָבֵא אִתְּךָ אֶת הַסֵּפֶר שֶׁלִּי כְּשֶׁתָּבוֹא.", fr: "Rapportez mon livre quand vous viendrez s'il vous plaît." },
      { he: "אַחֲרֵי אֲרוּחַת הָעֶרֶב תָּמִיד מִתְחַשֵּׁק לִי לִישֹׁן.", fr: "Après le dîner, j'ai toujours envie de dormir." },
      { he: "אַחֲרֵי אֲרוּחַת הָעֶרֶב תָּמִיד בָּא לִי לִישֹׁן.", fr: "Après le dîner, j'ai toujours envie de dormir." },
      { he: "הָיִיתִי רוֹצֶה לִרְאוֹת אוֹתוֹ מָחָר אַחַר הַצָּהֳרַיִם.", fr: "J'aimerais le voir demain après-midi." },
      { he: "לְמַעֲשֶׂה, מֵהַבֹּקֶר לֹא אָכַלְתִּי שׁוּם דָּבָר.", fr: "En fait, je n'ai rien mangé depuis ce matin." },
      { he: "יֵשׁ לָהּ אוֹתוֹ מִסְפַּר סְפָרִים כְּמוֹ לִי.", fr: "Elle a autant de livres que moi." },
    ],
  },
  {
    id: "r19",
    level: 5,
    theme: "general",
    words: 116,
    sentences: [
      { he: "הוּא הִגִּיעַ מֻקְדָּם כַּאֲשֶׁר הִתְבַּקֵּשׁ לָבוֹא מֻקְדָּם.", fr: "Il venait tôt quand on le lui demandait." },
      { he: "הוּא הִגִּיעַ מֻקְדָּם כַּאֲשֶׁר הִתְבַּקֵּשׁ לַעֲשׂוֹת זֹאת.", fr: "Il venait tôt quand on le lui demandait." },
      { he: "נָסַעְנוּ לְהָוָאִי בַּשָּׁנָה שֶׁעָבְרָה בַּפַּעַם הָרִאשׁוֹנָה.", fr: "Nous sommes allés à Hawai l'an dernier pour la première fois." },
      { he: "תֹּם הוּא תַּלְמִיד מַתְחִיל, אֲבָל הוּא לוֹמֵד מַהֵר.", fr: "Tom est débutant, mais il apprend vite." },
      { he: "הֵם הָיוּ עֲיֵפִים מִדַּי מִלְּטַפֵּס עַל הַר.", fr: "Ils étaient trop fatigués pour grimper une montagne." },
      { he: "הַרְשֵׁה לִי לְהַסְבִּיר לְךָ עַל מְנַת הַיּוֹם.", fr: "Permettez-moi de vous expliquer le plat du jour." },
      { he: "הַרְשִׁי לִי לְהַסְבִּיר לָךְ עַל מְנַת הַיּוֹם.", fr: "Permettez-moi de vous expliquer le plat du jour." },
      { he: "הַרְשׁוּ לִי לְהַסְבִּיר לָכֶם עַל מְנַת הַיּוֹם.", fr: "Permettez-moi de vous expliquer le plat du jour." },
      { he: "אִישׁ מֵהַתַּלְמִידִים לֹא יָכוֹל הָיָה לְהָשִׁיב עַל הַשְּׁאֵלָה.", fr: "Aucun étudiant ne put répondre à la question." },
      { he: "הִיא פָּתְחָה אֶת הַמִּכְתָּב בָּרֶגַע שֶׁהָיְתָה לְבַדָּהּ.", fr: "Elle ouvrit la lettre dès qu'elle fut toute seule." },
      { he: "צְמָחִים מֵתִים אִם אֵין לָהֶם מַיִם.", fr: "Les plantes meurent si elles manquent d'eau." },
      { he: "יֵשׁ הַרְבֵּה מִלִּים שֶׁאֲנִי לֹא מֵבִין.", fr: "Il y a beaucoup de mots que je ne comprends pas." },
      { he: "יֵשׁ הַרְבֵּה מִלִּים שֶׁאֲנִי לֹא מְבִינָה.", fr: "Il y a beaucoup de mots que je ne comprends pas." },
      { he: "אֲחוֹתִי עוֹבֶדֶת בְּשַׁגְרִירוּת אַרְצוֹת הַבְּרִית בְּלוֹנְדוֹן.", fr: "Ma sœur travaille à l'ambassade des États-Unis à Londres." },
      { he: "לַאֲמִתּוֹ שֶׁל דָּבָר, אֲנִי לֹא אוֹהֶבֶת אוֹתוֹ.", fr: "En fait, je ne l'aime pas." },
      { he: "לַאֲמִתּוֹ שֶׁל דָּבָר, אֲנִי לֹא אוֹהֵב אוֹתָהּ.", fr: "En fait, je ne l'aime pas." },
      { he: "אֲנִי קָם בְּדֶרֶךְ כְּלָל לִקְרַאת הַשָּׁעָה שְׁמוֹנֶה.", fr: "Je me lève habituellement vers 8 heures." },
    ],
  },
  {
    id: "r20",
    level: 5,
    theme: "transport",
    words: 112,
    sentences: [
      { he: "הוּא הֵרִים אֶת יָדוֹ כְּדֵי לַעֲצֹר מוֹנִית.", fr: "Il tendit le bras pour faire s'arrêter un taxi." },
      { he: "יוֹתֵר מַהֵר, אוֹ שֶׁנְּאַחֵר אֶת הָרַכֶּבֶת.", fr: "Plus vite, ou nous allons rater le train." },
      { he: "הִיא הֶרְאֲתָה לוֹ הֵיכָן לְהַנִּיחַ אֶת הַמִּזְוָדָה.", fr: "Elle lui a indiqué où poser la valise." },
      { he: "תַּגִּיד לִי מָתַי אַתָּה מַגִּיעַ לִשְׂדֵה הַתְּעוּפָה.", fr: "Dites-moi quand vous arrivez à l'aéroport." },
      { he: "תַּגִּיד לִי מָתַי אַתָּה מַגִּיעַ לִנְמַל הַתְּעוּפָה.", fr: "Dites-moi quand vous arrivez à l'aéroport." },
      { he: "תַּגִּידִי לִי מָתַי אַתְּ מַגִּיעָה לִשְׂדֵה הַתְּעוּפָה.", fr: "Dites-moi quand vous arrivez à l'aéroport." },
      { he: "תַּגִּידוּ לִי מָתַי תַּגִּיעוּ לִשְׂדֵה הַתְּעוּפָה.", fr: "Dites-moi quand vous arrivez à l'aéroport." },
      { he: "כַּמָּה יָמִים נִמְשֶׁכֶת בְּדֶרֶךְ כְּלָל הַנְּסִיעָה לְשָׁם?", fr: "Combien de jours dure d'habitude le voyage jusque là ?" },
      { he: "הִגַּעְתִּי בַּזְּמַן לִתְפֹּס אֶת הָרַכֶּבֶת שֶׁלִּי.", fr: "Je suis arrivé à temps pour mon train." },
      { he: "נִסִּיתִי לְהִתְקַשֵּׁר אֵלֶיךָ, אֲבָל לֹא יָכֹלְתִּי.", fr: "J'ai essayé de t'appeler mais je n'ai pas pu." },
      { he: "יֵשׁ לוֹ דַּי כֶּסֶף כְּדֵי לִקְנוֹת אֶת זֶה.", fr: "Il a assez d'argent pour l'acheter." },
      { he: "יֵשׁ לוֹ מַסְפִּיק כֶּסֶף כְּדֵי לִקְנוֹת אֶת זֶה.", fr: "Il a assez d'argent pour l'acheter." },
      { he: "גָּנְבוּ מִמֶּנִּי אֶת הַכַּרְטִיס הַבַּנְקַאי שֶׁלִּי בַּמֶּטְרוֹ.", fr: "On m'a volé ma carte bancaire dans le métro." },
      { he: "אָז אֲנִי יְכוֹלָה עֲדַיִן לִישֹׁן עוֹד חָמֵשׁ דַּקּוֹת.", fr: "Donc je peux encore dormir cinq minutes." },
      { he: "אָז אֲנִי יָכוֹל לִישֹׁן עֲדַיִן עוֹד חָמֵשׁ דַּקּוֹת.", fr: "Donc je peux encore dormir cinq minutes." },
      { he: "אֲנִי קָמָה בְּדֶרֶךְ כְּלָל לִקְרַאת הַשָּׁעָה שְׁמוֹנֶה.", fr: "Je me lève habituellement vers 8 heures." },
    ],
  },
  {
    id: "r21",
    level: 6,
    theme: "general",
    words: 142,
    sentences: [
      { he: "אֲנִי אוֹהֶבֶת יַיִן אָדֹם יוֹתֵר מֵאֲשֶׁר יָיִן לָבָן.", fr: "J'aime le vin rouge plus que le vin blanc." },
      { he: "אֲנִי אוֹהֵב יַיִן אָדֹם יוֹתֵר מֵאֲשֶׁר יַיִן לָבָן.", fr: "J'aime le vin rouge plus que le vin blanc." },
      { he: "אֲחוֹתִי הַקְּטַנָּה בִּקְּשָׁה מִמֶּנִּי לְלַמֵּד אוֹתָהּ לַעֲשׂוֹת סְקִי.", fr: "Ma petite sœur m'a demandé de lui apprendre à skier." },
      { he: "הוּא נָסַע לְלוֹנְדוֹן כְּדֵי לִלְמֹד אַנְגְּלִית.", fr: "Il vint à Londres pour étudier l'anglais." },
      { he: "הוּא הִגִּיעַ לְלוֹנְדוֹן כְּדֵי לִלְמֹד אַנְגְּלִית.", fr: "Il vint à Londres pour étudier l'anglais." },
      { he: "הָאִישׁ הוּא הַצַּיָּד, הָאִשָּׁה הִיא טַרְפּוֹ.", fr: "L'homme est le chasseur, la femme son gibier." },
      { he: "הוּא לֹא מַכִּיר אַף אֶחָד מֵאִתָּנוּ.", fr: "Il ne connaît aucun d'entre nous." },
      { he: "הֶחָתוּל שֶׁלִּי הָרַג אֶת הָעַכְבָּר הַזֶּה.", fr: "Mon chat a tué cette souris." },
      { he: "אֲנִי לֹא יוֹדֵעַ דָּבָר עַל הַקֶּשֶׁר בֵּינֵיהֶם.", fr: "Je ne connais rien de leur relation." },
      { he: "אֲנִי לֹא יוֹדַעַת דָּבָר עַל הַקֶּשֶׁר בֵּינֵיהֶם.", fr: "Je ne connais rien de leur relation." },
      { he: "אֱלֹהִים בָּרָא אֶת הָאָדָם בְּצַלְמוֹ, אֱלֹהִים הוּא לוֹחֵם.", fr: "Dieu créa l'homme à son image, Dieu est un guerrier." },
      { he: "הוּא מֵבִין פָּחוֹת אוֹ יוֹתֵר אֶת הַבְּעָיוֹת שֶׁלּוֹ.", fr: "Il comprend plus ou moins ses problèmes." },
      { he: "הֵם אוֹמְרִים בַּתַּחֲזִית שֶׁמָּחָר יִהְיֶה מְעֻנָּן.", fr: "Ils prévoient que ce sera nuageux demain." },
      { he: "ג'וֹן לֹא מְסֻגָּל לְדַבֵּר הֵיטֵב צָרְפָתִית.", fr: "John ne sait pas bien parler le français." },
      { he: "לֹא הִכַּרְתִּי כְּלָל אֶת הָאִשָּׁה הַזֹּאת.", fr: "Je ne connaissais absolument pas cette femme." },
      { he: "לֹא הִכַּרְתִּי בִּכְלָל אֶת הָאִשָּׁה הַזֹּאת.", fr: "Je ne connaissais absolument pas cette femme." },
      { he: "לְדַעְתִּי, יִהְיֶה קָשֶׁה לִפְתֹּר אֶת הַבְּעָיָה הַזֹּאת.", fr: "À mon avis, ce sera difficile de résoudre ce problème." },
      { he: "הוּא מְדַבֵּר כְּאִלּוּ הוּא יָדַע הַכֹּל.", fr: "Il parle comme s'il connaissait tout." },
      { he: "הוּא לָמַד בְּמֶשֶׁךְ שָׁעָה וָחֵצִי כָּל יוֹם.", fr: "Il étudia pendant une heure et demie chaque jour." },
      { he: "הוּא לָמַד כָּל יוֹם בְּמֶשֶׁךְ שָׁעָה וָחֵצִי.", fr: "Il étudia pendant une heure et demie chaque jour." },
      { he: "הִיא קָרְאָה אֶת הַסֵּפֶר בְּמֶשֶׁךְ כָּל הַלַּיְלָה.", fr: "Elle a lu le livre toute la nuit." },
    ],
  },
  {
    id: "r22",
    level: 6,
    theme: "greeting",
    words: 143,
    sentences: [
      { he: "תּוּכַל לְקַצֵּר אֶת זֶה מְעַט עֲבוּרִי?", fr: "Pourriez-vous me le raccourcir un peu ?" },
      { he: "תּוּכְלִי לְקַצֵּר אֶת זֶה מְעַט עֲבוּרִי?", fr: "Pourriez-vous me le raccourcir un peu ?" },
      { he: "קַח אֶת הַזְּמַן שֶׁלְּךָ. זֶה לֹא דָּחוּף.", fr: "Prends ton temps. Il n'y a pas d'urgence." },
      { he: "סְלַח לִי, אֲבָל הָאֱמֶת הִיא שֶׁ ...", fr: "Excusez-moi, mais la vérité c'est que ..." },
      { he: "הַרְשֵׁה לִי לְהַצִּיג אוֹתְךָ לְמַר טַנְקָה.", fr: "Laissez-moi vous présenter M. Tanaka." },
      { he: "אַתָּה יָכוֹל לָבוֹא לְבַקֵּר אוֹתִי מָתַי שֶׁתִּרְצֶה.", fr: "Tu peux venir me rendre visite quand tu veux." },
      { he: "אַתְּ יְכוֹלָה לָבוֹא לְבַקֵּר אוֹתִי מָתַי שֶׁתִּרְצִי.", fr: "Tu peux venir me rendre visite quand tu veux." },
      { he: "בּוֹאוּ נַעֲשֶׂה הַפְסָקָה בַּמָּקוֹם עִם נוֹף יָפֶה.", fr: "Faisons une pause dans un endroit avec une belle vue." },
      { he: "תּוּכַל לְהַגִּיד לִי מָה יֻצַּג בַּקּוֹלְנוֹעַ בַּשָּׁבוּעַ הַקָּרוֹב?", fr: "Pouvez-vous m'indiquer ce qu'il y aura au cinéma la semaine prochaine ?" },
      { he: "תּוּכְלִי לְהַגִּיד לִי מָה יֻצַּג בַּקּוֹלְנוֹעַ בַּשָּׁבוּעַ הַקָּרוֹב?", fr: "Pouvez-vous m'indiquer ce qu'il y aura au cinéma la semaine prochaine ?" },
      { he: "אַתָּה לֹא חַיָּב לְדַבֵּר כָּל כָּךְ חָזָק.", fr: "Tu n'es pas obligé de parler aussi fort." },
      { he: "אַתָּה יָכוֹל לִסְגֹּר אֶת הַחַלּוֹן, בְּבַקָּשָׁה?", fr: "Pourrais-tu fermer la fenêtre s'il te plaît ?" },
      { he: "אַתְּ יְכוֹלָה לִסְגֹּר אֶת הַחַלּוֹן, בְּבַקָּשָׁה?", fr: "Pourrais-tu fermer la fenêtre s'il te plaît ?" },
      { he: "תַּעֲשֶׂה מָה שֶׁנִּרְאֶה לְךָ הֲכִי טוֹב, בְּבַקָּשָׁה.", fr: "Faites ce qui vous semble le mieux, s'il vous plaît." },
      { he: "הָיִית צְרִיכָה לָבוֹא קְצָת יוֹתֵר מֻקְדָּם.", fr: "Tu aurais dû venir un peu plus tôt." },
      { he: "פָּגַשְׁתִּי אוֹתוֹ בְּמִקְרֶה אֶתְמוֹל בִּשְׂדֵה הַתְּעוּפָה.", fr: "Je l'ai rencontré par hasard hier à l'aéroport." },
      { he: "הַיּוֹם אֲנִי עוֹמֵד לָרוּץ חֲמִשָּׁה עָשָׂר קִילוֹמֶטְרִים!", fr: "Aujourd'hui je vais courir quinze kilomètres !" },
      { he: "אֲנִי רוֹצֶה לִתְפֹּס אֶת זֶה שֶׁל רֶבַע לַחֲצוֹת.", fr: "Je veux attraper celui de minuit moins le quart." },
      { he: "אֲנִי רוֹצָה לְהַסְפִּיק לָזֶה שֶׁל רֶבַע לַחֲצוֹת.", fr: "Je veux attraper celui de minuit moins le quart." },
      { he: "כָּל הָעוֹלָם רוֹצֶה לִפְגֹּשׁ אוֹתְךָ, אַתָּה מְפֻרְסָם!", fr: "Tout le monde veut te rencontrer, tu es célèbre !" },
      { he: "כָּל הָעוֹלָם רוֹצֶה לִפְגֹּשׁ אוֹתָךְ, אַתְּ מְפֻרְסֶמֶת!", fr: "Tout le monde veut te rencontrer, tu es célèbre !" },
    ],
  },
  {
    id: "r23",
    level: 6,
    theme: "family",
    words: 141,
    sentences: [
      { he: "הַדּוֹד שֶׁלִּי מַגִּיעַ לִרְאוֹת אוֹתָנוּ מָחָר.", fr: "Mon oncle vient nous voir demain." },
      { he: "אֲנִי חוֹשֵׁב שֶׁאַתָּה הֶחָבֵר הַטּוֹב בְּיוֹתֵר שֶׁלִּי.", fr: "Je pense que tu es mon meilleur ami." },
      { he: "אֲנִי חוֹשֶׁבֶת שֶׁאַתָּה הֶחָבֵר הַטּוֹב בְּיוֹתֵר שֶׁלִּי.", fr: "Je pense que tu es mon meilleur ami." },
      { he: "לַמִּשְׁפָּחָה שֶׁלּוֹ לֹא חָסֵר שׁוּם דָּבָר.", fr: "Sa famille ne manque de rien." },
      { he: "לַמִּשְׁפָּחָה שֶׁלָּהּ לֹא חָסֵר שׁוּם דָּבָר.", fr: "Sa famille ne manque de rien." },
      { he: "הָאֲנָשִׁים שֶׁגָּרִים כָּאן הֵם חֲבֵרִים שֶׁלָּנוּ.", fr: "Les gens qui vivent ici sont nos amis." },
      { he: "הִקְדַּשְׁתִּי אֶת כָּל תְּשׂוּמֶת לִבִּי לַנּוֹף בַּחוּץ.", fr: "Je plaçai toute mon attention sur le paysage dehors." },
      { he: "כָּרֶגַע אֲנִי גָּר אֵצֶל דּוֹד שֶׁלִּי.", fr: "En ce moment j'habite chez mon oncle." },
      { he: "אֲנִי אֶשָּׁאֵר כָּאן עַד שָׁעָה עָשָׂר.", fr: "Je reste ici jusqu'à 10 heures." },
      { he: "אֲנִי אֶקַּח אֶת זֶה עַל עַצְמִי.", fr: "Je prendrai soin de ça." },
      { he: "אֲנִי לֹא מַשְׁמִיץ אֶת הַיְּלָדִים שֶׁלָּהֶם.", fr: "Je ne leur déprave pas leurs enfants." },
      { he: "לֹא מְשַׁנֶּה מָה יִקְרֶה, אֲנִי אֶתְמֹךְ בָּךְ.", fr: "Quoi qu'il arrive, je vous soutiendrai." },
      { he: "אֲנִי אֲסַפֵּר לְךָ אֶת הַסִּפּוּר שֶׁלִּי.", fr: "Je te dirai mon histoire." },
      { he: "אֲנִי אֶעֱשֶׂה כָּל מָה שֶׁתְּבַקֵּשׁ מִמֶּנִּי.", fr: "Je ferai tout ce que vous me demanderez." },
      { he: "אֲנִי מַכִּיר טוֹב מְאוֹד אֶת אָחִיךָ.", fr: "Je connais très bien votre frère." },
      { he: "אֲנִי מַכִּירָה אֶת אָחִיךָ טוֹב מְאוֹד.", fr: "Je connais très bien votre frère." },
      { he: "אֲנִי נָשׂוּי וְיֵשׁ לִי שְׁנֵי יְלָדִים.", fr: "Je suis marié et ai deux enfants." },
      { he: "הוּא הִצִּיג בְּפָנַי אֶת הַבַּת שֶׁלּוֹ.", fr: "Il m'a présenté sa fille." },
      { he: "יֵשׁ לִי שְׁלוֹשָׁה אַחִים וְאַרְבַּע אֲחָיוֹת.", fr: "J'ai trois frères et quatre sœurs." },
      { he: "אֲנִי מַשְׁכִּיב אֶת יְלָדַי לִישֹׁן כָּל לַיְלָה.", fr: "Je borde mes enfants au lit tous les soirs." },
      { he: "אֲנִי לֹא יָכוֹל לְהַרְשׁוֹת לְעַצְמִי לִקְנוֹת מְכוֹנִית מְשֻׁמֶּשֶׁת.", fr: "Je ne peux pas me permettre d'acheter une voiture d'occasion." },
      { he: "אֲנִי לֹא יְכוֹלָה לְהַרְשׁוֹת לְעַצְמִי לִקְנוֹת מְכוֹנִית מְשֻׁמֶּשֶׁת.", fr: "Je ne peux pas me permettre d'acheter une voiture d'occasion." },
    ],
  },
  {
    id: "r24",
    level: 6,
    theme: "general",
    words: 146,
    sentences: [
      { he: "אִי אֶפְשָׁר לִרְאוֹת אֶת הָאָטוֹמִים בְּעַיִן בִּלְתִּי מְזֻיֶּנֶת.", fr: "Les atomes ne peuvent pas être vus à l'œil nu." },
      { he: "הוּא לֹא עָמַד עֲדַיִן עַל טָעוּיוֹתָיו.", fr: "Il n'a pas encore pris conscience de ses fautes." },
      { he: "יִקַּח זְמַן עַד שֶׁהוּא יַרְגִּישׁ יוֹתֵר טוֹב.", fr: "Il faudra du temps avant qu'il aille mieux." },
      { he: "אֵין אֲגַם גָּדוֹל יוֹתֵר בְּיַפָּן מֵאֲגַם בִּיוָה.", fr: "Au Japon il n'y a pas de lac plus grand que le lac Biwa." },
      { he: "מָה הַנּוֹשֵׂא שֶׁל הָרוֹמָן הָאַחֲרוֹן שֶׁלּוֹ?", fr: "Quel est le sujet de son dernier roman ?" },
      { he: "צֶדֶק הוּא כּוֹכַב הַלֶּכֶת הַגָּדוֹל בְּיוֹתֵר בְּמַעֲרֶכֶת הַשֶּׁמֶשׁ.", fr: "Jupiter est la planète la plus massive du système solaire." },
      { he: "הוּא הַשִּׂיא אֶת בֵּיתוֹ לְעוֹרֵךְ דִּין.", fr: "Il a marié sa fille à un avocat." },
      { he: "אֲנִי חוֹשֵׁב שֶׁהוּא לֹא יַגִּיד כֵּן.", fr: "Je pense qu'il ne dira pas oui." },
      { he: "לוֹקֵחַ שְׁעָתַיִם לִקְרֹא אֶת הַסֵּפֶר הַזֶּה.", fr: "Cela prend deux heures de lire ce livre." },
      { he: "הוּא יוֹדֵעַ טוֹב אֶת הַהִיסְטוֹרְיָה שֶׁל אַנְגְּלִיָּה.", fr: "Il connaît bien l'histoire de l'Angleterre." },
      { he: "אֲבָל הוּא מִשְׂחַק כַּדּוּרֶגֶל עִם חָבֵר שֶׁלּוֹ.", fr: "Mais il joue au football avec son ami." },
      { he: "הַבִּנְיָנִים קְטַנִּים בְּיַחַס לְגוֹרְדֵי הַשְּׁחָקִים שֶׁל נְיוּ-יוֹרְק.", fr: "Les immeubles sont petits comparés aux gratte-ciel de New York." },
      { he: "אֶחָד מֵחַבְרֵי בָּא לְבַקָּרֵי בְּמַהֲלַךְ הַיּוֹם.", fr: "Un de mes amis vint me voir pendant la journée." },
      { he: "אֵיךְ אַתָּה מַסְבִּיר אֶת הָעֻבְדָּה הַזֹּאת?", fr: "Comment expliquez-vous ce fait ?" },
      { he: "בֶּעָבָר, אֲנָשִׁים הָיוּ הוֹלְכִים בָּרֶגֶל מְאַדּוֹ עַד קִיוֹטוֹ.", fr: "Autrefois, les gens marchaient de Edo jusqu'à Kyoto." },
      { he: "אַרְמְסְטְרוֹנְג הָיָה הָאָדָם הָרִאשׁוֹן שֶׁהִגִּיעַ לַיָּרֵחַ.", fr: "Armstrong fut le premier homme à atteindre la lune." },
      { he: "אַף אֶחָד לֹא עוֹלֶה עָלָיו בְּבִקֹּרֶת עַל אֲחֵרִים.", fr: "Il n'a pas son égal quand il s'agit de critiquer les autres." },
      { he: "הֻפְתַּעְנוּ מֵהַקַּלּוֹת בָּהּ פָּתַר אֶת הַבְּעָיָה.", fr: "Nous avons été surpris par la facilité avec laquelle il a résolu le problème." },
      { he: "הִיא לֹא אָהֲבָה אֶת הַמְּגוּרִים בָּעִיר.", fr: "Elle n'aimait pas vivre en ville." },
      { he: "קְרִיאַת הָרוֹמָן הַזֶּה מְעַנְיֶנֶת תַּלְמִידִים מְעַטִּים.", fr: "Peu d'étudiants sont intéressés par la lecture de ce roman." },
      { he: "אֲחוֹתִי סוּזָן קָמָה מֻקְדָּם כָּל בֹּקֶר.", fr: "Ma sœur Susan se lève tôt tous les matins." },
      { he: "כַּמָּה סְפָרִים אַתָּה חוֹשֵׁב שֶׁקָּרָאתָ עַד עַכְשָׁו?", fr: "Combien de livres penses-tu avoir lu jusqu'à maintenant ?" },
    ],
  },
];
